- VaultSimC/Vault.cpp
- VaultSimC/Vault.h
- VaultSimC/libVaultSimGen.cpp
- VaultSimC/transaction.h
- on fly hmc op debugging: to debug if any hmc op is stocked in vaults or not. The program will give just a warning for once for each single HMC op and continue to execute
- use vault.debug_OnFlyHmcOps to enable it
- use vault.debug_OnFlyHmcOpsThresh to set what is the threshold
- Compute cost in cycles for each type of HMC operation has been added
- the default value is 0 cycle
> onFlyHMCop Debugs, Compute phase costs, small fixes

- merlin/test/nic.cc
- simpleElementExample/simpleMessageGeneratorComponent.h
Fixes some printf type warnings.
> Fix Type Print Warnings in Clang for Merlin and SimpleMessageGenerator

- VaultSimC/Makefile.am
- VaultSimC/VaultSimC.cpp
- VaultSimC/libVaultSimGen.cpp
- VaultSimC/logicLayer.cpp
- memHierarchy/cacheController.h
- memHierarchy/cacheEventProcessing.cc
- memHierarchy/cacheFactory.cc
- memHierarchy/coherenceControllers.h
- memHierarchy/libmemHierarchy.cc
- memHierarchy stat for hmc info
- HMC_FLAG used inside VaultSim to disable accessing HMC Type filed in memEvent when it is not defined
- remove warning message for param req_LimitPerCycle
> memHierarchy Stat, HMC_FLAG for VaultSim, minor fixes

- ariel/arielmemmgr.cc
- ariel/arielmemmgr.h
- ariel/frontend/simple/fesimple.cc
Support calls for standard malloc/free with mapping in the Ariel Simple Front End. This means all heap managed application memory can be tracked via Ariel.
> Support for C-standard malloc/free Calls in Ariel Simple Front End

- zodiac/zdumpi.cc
- zodiac/zdumpi.h
When DUMPI is enabled during configure the Zodiac interface does not contain updated code for the Hermes interface.
> Fixes error when compiling Zodiac and DUMPI is Enabled.

- memHierarchy/IncoherentController.cc
- memHierarchy/L1CoherenceController.cc
- memHierarchy/L1IncoherentController.cc
- memHierarchy/MESICoherenceController.cc
- memHierarchy/MESIInternalDirectory.cc
- memHierarchy/cacheArray.h
- memHierarchy/cacheController.cc
- memHierarchy/cacheEventProcessing.cc
- memHierarchy/cacheFactory.cc
- memHierarchy/coherenceControllers.h
- memHierarchy/directoryController.cc
- memHierarchy/dmaEngine.cc
- memHierarchy/libmemHierarchy.cc
- memHierarchy/memEvent.h
- memHierarchy/memNIC.cc
- memHierarchy/memNIC.h
- memHierarchy/memoryController.cc
memNIC now computes message size based on payload size (not # bytes requested)
Set #bytes requested correctly throughout coherence controllers (instead of assuming cache line granularity)
memNIC output stream is inherited from its component now
> memH: Fix requested size vs. size of message discrepancy in memEvent

- memHierarchy/Sieve/sieveController.cc
Small fix - patching a memory leak. 
It used to not de-allocate "free" events, so we leaked a few bytes every time the front-end did a free().
> fixed memory leak

- miranda/miranda.cc
Fixes bug #65. Adds a parameter definition to Miranda.
> Fix Miranda SpMV Missing Parameter

- miranda/miranda.cc
Fix Miranda library name as reported in bug: #116
> Fix Miranda library name as reported in bug: #116

- ember/mpi/motifs/emberrandomgen.h
Fixes an error in the Ember Random Gen Header file. Preprocessor guard is not correctly matched. Caught by LLVM compiler on Mac OSX.
> Fix Ember Random Gen Header File Guard Error

- miranda/tests/copybench.py
- miranda/tests/inorderstream.py
- miranda/tests/randomgen.py
- miranda/tests/revsinglestream.py
- miranda/tests/singlestream.py
- miranda/tests/stencil3dbench.py
- miranda/tests/streambench.py
Can address some slow down on Miranda tests in parallel environments by prevent cut on the link to L1 cache where traffic is heaviest.
> Miranda - Don't Allow Split of L1 Cache Link in Tests to Improve Performance in Multithreaded Environments

- merlin/merlin.cc
- merlin/portControl.cc
- merlin/portControl.h
Added a new statistic for idle_time in portControl.  This records the amount of time that a port was not transmitting data (due to a lack of credits or lack of data).  Needs to be reviewd by Scott H.
> Addition of idle_time Statistic to portControl

- ariel/arielcpu.cc
Fix destructor doesn't call ArielCore
> Add destructor call to Ariel cores in the main CPU definition

- ariel/arielalloctrackev.h
- ariel/arielcore.cc
- ariel/frontend/simple/fesimple.cc
- memHierarchy/Sieve/sieveController.cc
- memHierarchy/Sieve/sieveController.h
- memHierarchy/Sieve/sieveFactory.cc
- memHierarchy/libmemHierarchy.cc
Allows an application in ariel to use a ariel_output_stats_buoy() call to direct SST to drop stats. the _buoy() call can pass back a user-defined marker for the backend to label these stats. Currently, SieveController uses this to drop regular malloc() lists.
> changes to allow ariel to drop stats based on front-end command

- prospero/Makefile.am
- prospero/configure.m4
- prospero/runprosperotrace.cc
- prospero/tracetool/sstmemtrace.cc
Provides the `sst-prospero-trace` command to be run from SST `bin` directory. This tool knows/controls which PIN variant to launch and how to locate the default Prospero tracing tools. Has worked successfully in testing on Mac OS X and Linux.
> Add a Command to Run Prospero Profiling from SST Tool Directory

- prospero/Makefile.am
- prospero/runprosperotrace.cc
Provides a tool to correctly load PIN and perform a multi-threaded memory trace for Prospero. Appears that PIN detection and execution in testing for Prospero is not consistent with how Ariel is used even though both tools use PIN. This means Prospero will fail but Ariel will not. This tool provides the same launch mechanism as Ariel but for Prospero traces. Support is provided for `text`, `binary` and `compressed` traces.
> Provide a Tool to Generate Prospero Memory Traces

- miranda/generators/gupsgen.cc
- miranda/generators/gupsgen.h
there're *seed_a* and *seed_b* in the params, but they're never set, so it's not actually random...
> Fix miranda gups generator seeds not set problem

- VaultSimC/tests/sdl1.py
- memHierarchy/tests/sdl-1.py
- memHierarchy/tests/sdl-2.py
- memHierarchy/tests/sdl-3.py
- memHierarchy/tests/sdl2-1.py
- memHierarchy/tests/sdl3-1.py
- memHierarchy/tests/sdl3-2.py
- memHierarchy/tests/sdl3-3.py
- memHierarchy/tests/sdl4-1.py
- memHierarchy/tests/sdl4-2.py
- memHierarchy/tests/sdl5-1.py
- memHierarchy/tests/sdl8-1.py
- memHierarchy/tests/sdl8-3.py
- memHierarchy/tests/sdl8-4.py
- memHierarchy/tests/sdl9-1.py
- memHierarchy/tests/sdl9-2.py
Fixing params that are strings going into integers that is being used by new core params code.  Any empty string or invalid value will now throw an exception.  Old code would just return 0.
> Fix Incorrect string params 

- ariel/frontend/simple/fesimple.cc
Fix Ariel front end call to backtrace which doesn't exist in PIN headers
> Fix Ariel front end call to backtrace which doesn't exist in PIN headers

- ariel/arielcore.cc
Now utilize on-demand page allocation to reduce memory consumption.
> Ariel - Remove Malloc-based Page Allocation

- ember/mpi/motifs/ember3damr.cc
Fixes a bug in Ember where `ssh-meshconvert` is printed to screen when `sst-meshconvert` is correct name of tool. This caused user confusion because the tool name being printed could not be found. Should address Issue #293.
> Ember - Fix Error in Fatal Call where Tool is Named Incorrectly

- merlin/merlin.cc
- merlin/pymerlin.py
- merlin/topology/dragonfly2.cc
- merlin/topology/dragonfly2.h
The new relative global route mode interprets the global
link map differently.  Numbers in the link map are taken
as relative offsets from the current group, instead of as
an absolute number with the current group removed.  The
translation from global link map entry to raw group number
and global slice is the same for both modes.  However, the
raw group numbers are converted to actual group number
differently.
> Added relative global route mode.

- src/sst/elements/VaultSimC/Makefile.am
- src/sst/elements/cassini/Makefile.am
- src/sst/elements/ember/Makefile.am
- src/sst/elements/firefly/Makefile.am
- src/sst/elements/hermes/Makefile.am
- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/merlin/Makefile.am
- src/sst/elements/miranda/Makefile.am
- src/sst/elements/savannah/Makefile.am
- src/sst/elements/thornhill/Makefile.am
- src/sst/elements/zodiac/Makefile.am
Modifies several `Makefile.am` files so that the elements build can be performed "out-of-source".
> Fix Makefile.am files Needed for Out-of-Source Builds to Work Correctly

- src/sst/elements/ember/Makefile.am
- src/sst/elements/firefly/Makefile.am
- src/sst/elements/thornhill/Makefile.am
Add the header files to the Makefile.am files.    It's been a while since make-dist has run to look at the unemerated, but required header files.
> all the Makefile AM changes

- src/sst/elements/ariel/arielcore.cc
Prints an error message when an `ArielCommand` decode fails rather than asserts. @gvoskuilen has encountered some issues with the very latest Ariel.
> Print helpful messages when ArielCommand decode fails.

- src/sst/elements/merlin/test/nic.cc
- src/sst/elements/merlin/test/nic.h
- src/sst/elements/merlin/test/simple_patterns/shift.h
This functionality has been replace by ShareRegion.
> Remove references to SimpleNetwork::Mapping.

- src/sst/elements/ariel/arielcpu.cc
Also initialized child_pid so that the error handlers that cause
fatal() do not kill all processes (this was killing our Jenkins client
apps).  This does not explain why PIN is failing to start, only
improves the handling of the errors when it fails to start.
> Improved error messages if ariel fails to launch PIN

- src/sst/elements/merlin/pymerlin.py
In pymerlin module, the *TrafficGenEndPoint* class has a *nicKeys* variable that is used to hold the keys for traffic generators, it was set based on different patterns but it was never used. As a result, some of the params for certain traffic patterns will be missing, especially for those who doesn't have a default params, such as *HotSpot*.
In commit 0c20626 I added it to the *build* method so that it will ask for user input for missing params of the traffic pattern. 
In commit cb92912 I expanded the pattern check with *Exponential* pattern, which is present in *merlin/trafficgen/traficgen.cc* but was not in the pymerlin module.
> Fix pymerlin nickeys

- src/sst/elements/prospero/runprosperotrace.cc
Switches over Prospero to use `-injection child` instrumentation.
> Prospero PIN Change to use Child Injection Instrumentation

- src/sst/elements/memHierarchy/membackend/pagedMultiBackend.cc
- src/sst/elements/scheduler/allocators/BestFitAllocator.cc
Eliminate use of TYPENAME_MAX macros from C in favor of using std::numeric_limits<type>::max() calls which ensure better compliance with C++11.
> Eliminates use of *_MAX in favor of std::numeric_limits<type>::max()

- src/sst/elements/prospero/runprosperotrace.cc
Fix warnings introduced in use of `-injection child` parameter setting for PIN.
> Fix Warnings in Prospero Run Tools

- src/sst/elements/pyproto/pyarchive.cc
- src/sst/elements/pyproto/pyarchive.h
- src/sst/elements/pyproto/pyproto.h
PyProto no longer supports translating SST Events into Python objects.
Hopefully this will return at some point with a new serialization
mechanism.
> Remove Boost Serialization references

- src/sst/elements/scheduler/allocators/GranularMBSAllocator.cc
- src/sst/elements/scheduler/allocators/LinearAllocator.cc
- src/sst/elements/scheduler/allocators/MBSAllocator.cc
- src/sst/elements/scheduler/allocators/OctetMBSAllocator.cc
- src/sst/elements/scheduler/allocators/RoundUpMBSAllocator.cc
- src/sst/elements/scheduler/allocators/SortedFreeListAllocator.cc
- src/sst/elements/scheduler/schedulers/EASYScheduler.cc
- src/sst/elements/scheduler/schedulers/PQScheduler.cc
- src/sst/elements/scheduler/schedulers/StatefulScheduler.cc
- src/sst/elements/scheduler/taskMappers/TopoMapper.cc
Added `#include` for `cmath` and `algorithm`.
Exposed by serialization changes in core.
> Scheduler - Fix Missing Header Files for Serialization

- src/sst/elements/scheduler/taskMappers/TopoMapper.cc
Fix to Scheduler to address missing algorithm `#include`.
> Scheduler Fix for Missing Algorithm Includes

- config/sst_check_ptrace_set_tracer.m4
- configure.ac
- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/configure.m4
Adds configure time detection of whether `PR_SET_PTRACER` is defined since this is not available on kernels older than Linux 3.X. If not detected then Ariel will ignore this code.
> Ariel fix ptracing

- src/sst/elements/ariel/Makefile.am
Leading Tab in Makefile.am  causes undesired change in meaning
> Fix alignment in Makefile.am

- src/sst/elements/memHierarchy/bus.h
Remove extraneous #includes of boost serialization headers.
> Remove references to boost serialization headers

- src/sst/elements/scheduler/DragonflyMachine.cc
- src/sst/elements/scheduler/StencilMachine.cc
- src/sst/elements/scheduler/Torus3DMachine.cc
Solution to issue #424.
In archlinux the compiler did not find the math library functions. Added an include in files with issue.
> Solved a compilation issue in Archlinux

- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/memoryController.cc
Fixes an issue (#433) which is caused by the renaming of `sstinfo` to `sst-info` for consistency across SST binaries.
> Fix SST-Info renaming in MemHierarchy Stats Messages

- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/membackend/delayBuffer.cc
- src/sst/elements/memHierarchy/memoryController.cc
Fixes a series of compiler warnings and minor code errors in MemHierarchy. These appear on Mac when using clang.
> Fix MemHierarchy Compiler Warnings with Printf and Minor Code Errors

- src/sst/elements/merlin/router.h
RtrEvent::injectionTime was not being serialized, resulting in errors for multi-rank runs.
> Now serializing RtrEvent::injectionTime.

- src/sst/elements/memHierarchy/libmemHierarchy.cc
> Fixes New Line in MemHierarchy SST-Info Output (Bug reported in Issue #455)

- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/miranda/tests/goblin_singlestream1-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream1.py
- src/sst/elements/miranda/tests/goblin_singlestream2-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream2.py
- src/sst/elements/miranda/tests/goblin_singlestream3-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream3.py
Adds the ability to enable/disable device power tracing in Goblin HMC-Sim version 3.0+ (upstream). This patch adds "trace-power" to the goblinHMCSim component parameters to enable/disable HMC_TRACE_POWER. The current tracing output is written to the hmc-trace.out trace file.  Reworking pull request following github fail.  
Power tracing values include: 
— Link Phy
— Link Local Route (route of packet to local quadrant)
— Link Remote Route (route of packet to distant quadrant)
— Crossbar Request Slot (active SRAM/register state)
— Crossbar Response Slot (active SRAM/register state)
— Crossbar External Route (Cube-to-Cube route minus link phy)
— Vault Request Slot
— Vault Response Slot
— Vault Controller
— Row Access (inclues pre-charge+activate+fetch+sense)
> New feature

- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
This PR will allow HMCSim v2.0 to compile against the SST. For HMC v3.0 power modeling is also found and compiled into the code.
(see @gvoskuilen @allevin)
> MemHierarchy/Goblin HMCSim - Fix v2.0 with Errors because of HMC_POWER Modeling Options

- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.h
- src/sst/elements/miranda/tests/goblin_singlestream2-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream2.py
- src/sst/elements/miranda/tests/goblin_singlestream3-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream3.py
adding logic to initialize the DRAM latency timing information; this requires the use of HMC-Sim 3.0+ as there is a new function interface to initialize the timing info.  All the changes in the goblinHMCBackend are bounded by "HMC_DEF_DRAM_LATENCY" macros in order to protect backward compatibility.  
* These branches …
> adding logic to initialize the DRAM latency timing information

- src/sst/elements/zodiac/zsirius.cc
'trace' is initialized in ::setup(), and thus not available
in the destructor when run-mode=init.  However, it hasn't been
explitictly initialized to NULL either.  Fix that.
> Fix sst-core#3:  Zodiac crashes with 'run-mode=init'

- src/sst/elements/CramSim/tests/test_txntrace4.py
Remove explicit "split on space" and use the implicit "Split on whitespace"  to avoid get extra newline in SST generated Python file.
> Change test input file for compatibility with output config

- src/sst/elements/memHierarchy/membackend/backing.h
- src/sst/elements/merlin/merlin.h
- src/sst/elements/merlin/trafficgen/trafficgen.h
Removes boost from merlin library.  Also adds a necessary header in memHierarchy that was being included through the boost includes in core.  This is in preparation for removing boost from the core.
> Remove boost references in merlin

- src/sst/elements/CramSim/c_Dimm.cpp
- src/sst/elements/CramSim/c_DramSimTraceReader.cpp
- src/sst/elements/CramSim/c_TracefileReader.cpp
- src/sst/elements/CramSim/c_USimmTraceReader.cpp
- src/sst/elements/scheduler/Factory.cc
- src/sst/elements/scheduler/faultInjectionComponent.cc
With the removal of boost from the core, many files needed to directly
include the <algorithm> header file.
> Added required header files.

- src/sst/elements/memHierarchy/membackend/memBackendConvertor.cc
Valgrind was reporting use of uninitialized variable in some statistics.  Tracked down to this variable being uninitialized.   In C++, POD typed member variables are not initialized to zero.
> Fix uninitialized variable

- src/sst/elements/CramSim/Makefile.am
- src/sst/elements/CramSim/c_TracefileReader.hpp
- src/sst/elements/CramSim/configure.m4
Cramsim was only requiring boost due to an include file.  Removed the include and changed the configure.m4 and makefile.am files.
> Remove boost from CramSim

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/cacheEventProcessing.cc
- src/sst/elements/memHierarchy/configure.m4
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/mshr.cc
- src/sst/elements/memHierarchy/mshr.h
Removed the use of boost::variant in mshr.h.  Replace it with AddrEventVariant, which is a variant-like implementation for the specific case of types Addr and MemEvent*.
> Memh remove boost

- src/sst/elements/memHierarchy/configure.m4
Fixes bug where if a .ignore is put in prospero, autogen fails on memH.
> MemH: Fix configure to add USE_LIBZ

- src/sst/elements/ariel/frontend/simple/examples/stream/runstream.py
- src/sst/elements/ariel/frontend/simple/examples/stream/runstreamNB.py
- src/sst/elements/ariel/frontend/simple/examples/stream/runstreamSt.py
Updating test scripts for ariel to reflect changes in memHierarchy. This in reference to issue https://github.com/sstsimulator/sst-elements/issues/711
New PR to correct branch.
> Update ariel test scripts for issue 711

- config/sst_check_hbmdramsim.m4
Fixing autoconf issues with DRAMSim2 and HBMDRAMSim2 colliding.  This requires a change in the symbols for DRAMSim2( see https://github.com/tactcomplabs/HBM/commit/6668b3687f5b54dddaa70e97dbf1eb0956c65b0b)
This is a fix for bug #727 
---
* These branches are syncronized with the devel branch of sst-elements.  This is …
> fixing autoconf caching issue between DRAMSim2 and HBMDRAMSim2

- src/sst/elements/VaultSimC/VaultSimC.cpp
- src/sst/elements/ariel/arielcpu.cc
Also add error string to Ariel's fork fail message
> Don't mmap unused backing store in VaultSim

- src/sst/elements/memHierarchy/libmemHierarchy.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.h
Converting the goblinHMCBackend to utilize the recently merged ExtMemBackend infrastructure.  The goblin backend has been updated to utilize the incoming flag field such that it will now support posted write requests (similar to the posted request support in the scratchpad memHierarchy component).  This pull request has been tested to pass against all the goblinHMCBackend tests.
---
* Pull Requests will be …
> converting goblinHMCBackend to utilize ExtMemBackend infrastructure

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/libmemHierarchy.cc
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.h
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.h
- src/sst/elements/memHierarchy/membackend/memBackend.h
- src/sst/elements/miranda/tests/goblin_singlestream1-trace-map.py
- src/sst/elements/miranda/tests/goblin_singlestream1-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream1.py
- src/sst/elements/miranda/tests/goblin_singlestream2-trace.py
- src/sst/elements/miranda/tests/goblin_singlestream2.py
- src/sst/elements/miranda/tests/goblin_singlestream3.py
Backend logic for mapping existing memory requests to any other request type in goblinHMCbackend.  This also includes the necessary parameter logic to map CMC command structures as the backing request type for those commands.  This set of commits also includes a new ExtMemBackendConvertor that successfully converts the memory requests for all existing types to what is now necessary in the ExtMemBackend types.  
Note: The find_array parameter passing is currently broken on the SST Core Master TOT.  I'm sending this pull request now as the included patches have tests that can be used to reproduce the issue.  
---
----
> backend logic for mapping existing memory requests to any other request type in goblinHMCbackend

- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
fixing parsing and library loading issues in the cmd-config options 
testing against HMC-Sim Master (3.0) to load and execute normal I/O commands against CMC commands
This commit signals the basic ability to map an arbitrary set of incoming I/O requests via standard MemEvents to any HMC command.  This includes normal memory commands (RD/WR), Atomics and user-defined CMC commands.  
Additional python config options: 
"backend.cmd-map" : "[RD:64:CMC125]" where [{WR|RD|CUSTOM}:SIZE_IN_BYTES:TARGET_CMD]
"backend.cmd-config" : "[/path/to/libcmc.so:CMC_CMD_ID:RQST_FLITS:RESPONSE_FLITS]"
The goblin backend now requires the following config: 
"backendConvertor" : "memHierarchy.extMemBackendConvertor",
"backend" : "memHierarchy.goblinHMCSim",
> fixing parsing and library loading issues in the cmd-config options

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/amoCustomCmdHandler.cc
- src/sst/elements/memHierarchy/amoCustomCmdHandler.h
- src/sst/elements/memHierarchy/customCmdMemory.h
adding skeleton for amo custom command handler; this will eventually include basic AMO type support (one per customcmd).  this version compiles and links, but is not tested.
> adding skeleton for amo custom command handler

- src/sst/elements/memHierarchy/amoCustomCmdHandler.cc
- src/sst/elements/memHierarchy/amoCustomCmdHandler.h
- src/sst/elements/memHierarchy/customCmdMemory.h
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.h
Need to overhaul all the remaining memConvertors as well before everything is merged into devel.  This permits compilation with the goblinHMCSim membackend.
> fixing memory backend convertor for ExtMemBackends

- src/sst/elements/memHierarchy/amoCustomCmdHandler.cc
- src/sst/elements/memHierarchy/customCmdMemory.h
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/extMemBackendConvertor.h
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.h
- src/sst/elements/memHierarchy/membackend/memBackend.h
connecting correct request structure to extMemBackendConvertor
adding ExtMemBackend interface to handle custom incoming commands
need access to uint32_t command field in CustomCmdInfo
The ExtMemBackend type now has an optional template for issuing "issueCustomRequest" commands.  This should only be utilized when the backend supports custom memory requests through the custom memory request path.  The request ID's are now hooked up to the CustomCmdInfo structure.  However, we still need an integer identifier to uniquely classify individual requests coming all the way down from a processor model.  As soon as we have this, we can build the necessary command mappers in the memBackend to handle any potential custom requests.
> connecting correct request structure to extMemBackendConvertor

- src/sst/elements/memHierarchy/customcmd/amoCustomCmdHandler.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/directoryController.h
- src/sst/elements/memHierarchy/libmemHierarchy.cc
- src/sst/elements/memHierarchy/tests/goblinCustomCmdDC.py
- src/sst/elements/memHierarchy/tests/miranda.cfg
- src/sst/elements/memHierarchy/tests/utils.py
Bug fixes to the directoryController code to handle cached custom memory requests.  Added statistics to directoryController for custom commands.  Test to verify functional shootdowns in the presence of custom memory commands.  Execute the test as follows (from src/sst/elements/memHierarchy/tests/goblinCustomCmdDC.py): 
sst [-v] goblinCustomCmdDC.py
The test requires the goblinHMCBackend to be enabled (as this is the only backend that currently supports custom commands)
> Bug fixes and tests for cache coherency shootdowns with custom memory commands

- src/sst/elements/CramSim/c_Dimm.cpp
- src/sst/elements/CramSim/c_MemhBridge.hpp
- src/sst/elements/CramSim/memReqEvent.hpp
- src/sst/elements/Messier/Messier_Event.h
- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/Messier/WriteBuffer.cc
- src/sst/elements/Messier/WriteBuffer.h
- src/sst/elements/ember/tools/spygen/spygen.cc
- src/sst/elements/firefly/nicEvents.h
- src/sst/elements/firefly/simpleMemoryModel.h
- src/sst/elements/memHierarchy/customcmd/customCmdEvent.h
- src/sst/elements/memHierarchy/memTypes.h
- src/sst/elements/memHierarchy/membackend/memBackendConvertor.h
Cleanup compile warnings for clang and gcc before the latest release.
Tested XCode 8 and 9, and GCC 4.8 & 5.4
> Cleanup compile warnings for clang and gcc before the latest release.

- src/sst/elements/CramSim/c_Dimm.cpp
Cramsim fails to compile on gcc 5.4 on CentOS 7, but does work properly on Ubuntu 16.04.  Need to add the cmath library to compile.
> Fixed compile error for Cramsim when using gcc 5.4 on CentOS 7

- src/sst/elements/memHierarchy/membackend/HBMpagedMultiBackend.h
Bug fix to HBMpagedMultiBackend typos on master branch.  Fixes two basic typos to get a clean build.  This is a fix for Issue #814 
Tested against SST-Core master branch.  Tests performed using TactCompLabs HBMDramSim2 regression suite.
> bug fix to HBMpagedMultiBackend to correct typos

- src/sst/elements/memHierarchy/tests/hbm-2-trace.py
- src/sst/elements/memHierarchy/tests/hbm-2.py
- src/sst/elements/miranda/tests/hbm_singlestream1-trace.py
- src/sst/elements/miranda/tests/hbm_singlestream1.py
fixing HBMDramSim test fixtures to reflect new subcomponent name
This fixes the currently failing tests for HBMDRAMSim2.  The only change here is to enforce the new naming convention when loading the subcomponent through memHierarchy.
> fixing HBMDramSim test fixtures to reflect new subcomponent name

- config/sst_check_stake.m4
- src/sst/elements/miranda/Makefile.am
- src/sst/elements/miranda/configure.m4
- src/sst/elements/miranda/generators/stake.cc
- src/sst/elements/miranda/generators/stake.h
- src/sst/elements/miranda/miranda.cc
Adding the Stake "generator" subcomponent to Miranda.  This subcomponent provides a shim layer for the RISC-V "Spike" simulator to drive the SST memory simulation components.  All the standard functional simulation layers in the RISC-V Spike (riscv-isa-sim) infrastructure remain.  Stake provides a simple generator with a C-based callback routine that allows Spike to directly send memory requests to SST.  With these commits, we can directly drive memory experiments with RISC-V ELF binaries (including booting Linux on Spike)
Caveats: 
- This requires a modified riscv-isa-sim that is currently located here: https://github.com/tactcomplabs/riscv-isa-sim/tree/sst
- Atomic and custom memory operations are currently mapped to read requests.  We will update this in future commits to provide more …
> Adding Stake Miranda subcomponent that fuses RISC-V Spike simulator to SST for memory simulation

- src/sst/elements/ember/tests/refFiles/test_EmberSweep.out
- src/sst/elements/firefly/merlinEvent.h
- src/sst/elements/firefly/nic.cc
- src/sst/elements/firefly/nic.h
- src/sst/elements/firefly/nicEntryBase.cc
- src/sst/elements/firefly/nicEntryBase.h
- src/sst/elements/firefly/nicRdmaStream.cc
- src/sst/elements/firefly/nicRecvCtx.cc
- src/sst/elements/firefly/nicRecvCtx.h
- src/sst/elements/firefly/nicRecvMachine.h
- src/sst/elements/firefly/nicRecvStream.cc
- src/sst/elements/firefly/nicRecvStream.h
- src/sst/elements/firefly/nicSendEntry.h
- src/sst/elements/firefly/nicSendMachine.cc
- src/sst/elements/firefly/nicSendMachine.h
- src/sst/elements/firefly/nicShmem.cc
- src/sst/elements/firefly/nicShmemMove.cc
- src/sst/elements/firefly/nicShmemMove.h
- src/sst/elements/firefly/nicShmemSendEntry.h
To keep control messages from getting backed up behind long messages it was sent out over VC1. Control messages are now sent over VC0 (with standard messages). Control messages do not have to wait until pending long messages complete. The receive machine checks for control messages and processes them immediately.
> Move control messages to the "standard" VC

- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/portControl.cc
- src/sst/elements/merlin/portControl.h
- src/sst/elements/merlin/pymerlin.py
- src/sst/elements/merlin/topology/dragonfly.cc
- src/sst/elements/merlin/topology/dragonfly.h
- src/sst/elements/merlin/topology/dragonfly2.cc
- src/sst/elements/merlin/topology/dragonfly2.h
Removed old dragonfly topolgy and made it identical to dragonfly2.
Development on dragonfly2 will now stop and all future changes
will be done to dragonfly.
Added options to output_queue_length computation.
Can now track for a whole port instead of per VC by setting
oql_track_port to true.  Can also track an approximation of
output queue length and next router input queue length by
setting oql_track_remote to true.
> Merlin topo changes

- config/sst_check_stake.m4
This patch fixes an issue with the SST-Elements Stake configure process.  The latest versions of the the spike simulator require us to link against the RISC-V soft float library.  
---
> fixing the autoconf script for SST Stake

- src/sst/elements/ariel/ariel_shmem.h
- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/arielwriteev.h
- src/sst/elements/ariel/frontend/simple/fesimple.cc
Allows optional capture of write values ("application data") for forwarding into the memory system when using Ariel. This is the first commit which actively tracks instructions with clear stores. The application ELF data segment is not loaded so the mapping of some data will still not be correct.
> Capture Data Values for Writing Back to Memory Model when using Ariel

- src/sst/elements/ariel/arielcore.cc
Fix for Issue https://github.com/sstsimulator/sst-elements/issues/1056. Now, a fence will only occur if there are still outstanding transactions.
> Fix for fence stalls when the pending queue is empty

- src/sst/elements/miranda/generators/stake.cc
Following the latest merge of the SST "Stake" Spike simulator, we found that the top-level simulation class changed its default constructor.  As a result, we were forced to update the Stake miranda generator in order to support the upstream development version of the riscv-isa-sim (Spike).  This pull request enables users to utilize the latest revision of Spike (thus supporting the latest updates to the SBI).
> updating stake initialization to match upstream riscv-isa-sim

- src/sst/elements/miranda/generators/stake.cc
Compiling SST-Elements (master or devel) with Stake enabled would throw several warnings regarding the printing of Stake configuration options using the standard SST "out->verbose(...)" method.  This patch fixes those warnings by correctly specifying the incoming data types and/or c_str()-ized versions of C++ strings.  The remaining warnings indicate macro collisions with the Spike simulator source.  These will likely need to be fixed in the Stake riscv-isa-sim source.
> fixing warnings in printing Stake configuration options

- src/sst/elements/memHierarchy/Sieve/sieveController.cc
- src/sst/elements/memHierarchy/Sieve/sieveController.h
- src/sst/elements/memHierarchy/Sieve/sieveFactory.cc
At some point, the memSieve component could have a cacheListener attached to make a histogram of accesses (a gold output file and vestigial parameters in a test script indicate this). However, this ability seems to have been lost. I added it back in.
> added (back?) the ability to attach a CachListener to MemSieve

- src/sst/elements/memHierarchy/customcmd/customCmdMemory.h
- src/sst/elements/memHierarchy/customcmd/customOpCodeCmd.h
This was throwing an error in gcc's address sanitizer, because
CustomCmdInfo gets deleted through the base pointer at one point.
> Add virtual destructors for custom command info classes

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/mpi/embermpigen.h
- src/sst/elements/ember/mpi/motifs/emberotf2.cc
- src/sst/elements/ember/mpi/motifs/emberotf2.h
Provides initial support for OTF2-based traces which can be used as an Ember motif.
> Initial Support for OTF2-based Traces as an Ember Motif

- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheEventProcessing.cc
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.h
- src/sst/elements/memHierarchy/coherentMemoryController.cc
- src/sst/elements/memHierarchy/coherentMemoryController.h
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/memEventBase.h
- src/sst/elements/memHierarchy/memHierarchyInterface.cc
- src/sst/elements/memHierarchy/memHierarchyScratchInterface.cc
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/scratchpad.cc
- src/sst/elements/memHierarchy/tests/refFiles/test_memHA_CustomCmdGoblin_1.out
- src/sst/elements/memHierarchy/tests/refFiles/test_memHA_CustomCmdGoblin_1_MC.out
Update to turn off silent evictions for coherent memory controllers
Also enable setting the mshr_latency parameter for L1s
> MemH: Fix for coherent shootdowns

- src/sst/elements/merlin/target_generator/uniform.h
Fixed a typo in uniform target generator model that initialized the random number generator of all endpoints to the same value.
> Target get fix for uniform distribution 

- src/sst/elements/ember/shmem/motifs/emberShmemGetNBI.h
- src/sst/elements/firefly/nicShmem.cc
- src/sst/elements/firefly/nicShmemStream.cc
For the case of a non-blocking get the outstanding operation count was getting decremented before the get response was completely received.
> fix nonblocking SHMEM get

- src/sst/elements/scheduler/allocators/DflyHybridAllocator.cc
- src/sst/elements/scheduler/allocators/DflyJokanovicAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRDGAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRDRAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRRNAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRRRAllocator.cc
- src/sst/elements/scheduler/allocators/DflySlurmAllocator.cc
I contributed my dragonfly-machine allocators a month ago.
Now I remove those unnecessary outputs calling std::cout, because they are not recommended to use.
> Remove std::cout in dragonfly-machine allocators

- src/sst/elements/memHierarchy/memNIC.cc
- src/sst/elements/memHierarchy/memNIC.h
Allows memH to query for network link controls so we can load non-merlin-based networks.
> Allow memH to Select Link Control to Load

- src/sst/elements/simpleElementExample/simpleParamComponent.cc
- src/sst/elements/simpleElementExample/simpleParamComponent.h
- src/sst/elements/simpleElementExample/tests/test_simpleParamComponent.py
Adds a component to test core parameter passing/handling. This has been raised as a potential bug in SST core.
> Add a Params Processing Simple Example to test Core Parameter Handling

- src/sst/elements/merlin/portControl.cc
Found issue where idle time in merlin was reporting times greater than the simulation time.
The removed code seemed to reset the idle time to 0 and not do anything else.
Same as Merlin fix idle time statistic #1242 but without 30 commits due to rebasing correctly. 
* These branches are syncronized with the devel …
> Merlin fix idle time statistic

- src/sst/elements/shogun/arb/shogunarb.h
- src/sst/elements/shogun/arb/shogunrrarb.cc
- src/sst/elements/shogun/arb/shogunrrarb.h
- src/sst/elements/shogun/shogun.cc
- src/sst/elements/shogun/shogun.h
This fixes the bug described in issue https://github.com/sstsimulator/sst-elements/issues/1253. Overwrites the num_events variable with input_message_slots and uses this to limit the number of messages retrieved from inputQueues[] each arbitration cycle.
> Bug Fix for Issue 1253

- src/sst/elements/miranda/generators/revsinglestream.cc
- src/sst/elements/miranda/generators/revsinglestream.h
- src/sst/elements/miranda/generators/singlestream.h
- src/sst/elements/miranda/tests/revsinglestream.py
Help for SingleStream was incorrect; it listed the parameters start_at and stop_at but the subcomponent expects startat and stopat.
Updated ReverseSingleStream to be consistent with other subcomponents, using startat and stopat.
This is a fix for https://github.com/sstsimulator/sst-elements/issues/1302
> Updated SingleXStream

- src/sst/elements/miranda/generators/stake.cc
- src/sst/elements/miranda/generators/stake.h
This is a small fix for Issue #1305.  It repairs the Stake miranda generator interfaces for the Stake class in order to adhere to the latest interface standard for generators.  This was tested against the sst-elements devel branch from 07/01/2019 and the sst-core master branch from 07/01/2019.
> fix for Issue #1305; Repairing Stake class interfaces

- config/sst_check_gpgpusim.m4
New configure flag: --with-gpgpusim
Balar also updated to accept 	GPGPUSIM_LIBDIR and  GPGPUSIM_LIB, which should point to the modified cudart library, cudart_mod.
> Added GPGPU-Sim configure option

- config/sst_check_gpgpusim.m4
Older versions of autoconf leave the else part of AC_CHECK_FILE (file, [action-if-found], [action-if-not-found]) intact but empty, causing an error. New versions omit else if the action is empty in the macro.
if test "x$as_val" = x""yes; then
#Do STUFF
else
fi
> Temp Fix for Older autoconf

- config/sst_core_check_install.m4
This PR is to address issue #1417.
During configure, --with-sst-core=corepath will improperly find an previously built core if it is in the $PATH rather than the user defined "corepath".
Basically if a previously built core in the the $PATH, the --with-sst-core will find that one rather than the corepath defined by the user. The configure script will report which one it found, but if the user does not double check, they may believe that the configure worked and selected the corepath they wanted. This can cause a newer SST-Elements to be built with an older SST-core (that might be defined in the path).
There are basically 3 changes:
1 - Lines 10 and 19 fix incorrect logic.  This test was always failing because $with_sst_core actually returns the user defined path, not a "yes".  This caused …
> Changes to fix sst-core detect if another core is in the path

- config/sst_core_check_install.m4
Added message to the configure output stream when the checks for valid --with-sst-core are correct.  On RHEL6/CentOS6, these were causing mismatched if-then-else statements in the generated configure script.  However on RHEL7 and above, we did not seem to have a problem.
> Fixed the sst_core_check_install.m4 to handle RHEL6/CentOS6 issues

- configure.ac
Implement a generic method to mark an element as deprecated.  
This is a similar technique adding the .ignore into the element directory to have it ignored during autogen/configure.
we just add a hidden file called `.deprecated` and the configure script will detect it and mark the the element as YES - DEPRECATED in the configuration summary.
The real code changes happen on line 179 (my editor decided to clean up the extra whitespace...)
First element to be marked is scheduler
@gvoskuilen can you review before I release to the autotester?
> Implement a generic method to mark an element as deprecated.

- src/sst/elements/miranda/mirandaCPU.cc
- src/sst/elements/miranda/mirandaGenerator.h
Fix to bizarre behavior observed by other pull requests. On GCC 4.8.5 on a particular fork of core, request IDs were getting reset to zero causing event ordering differences.
> move miranda counter to single class definition

- src/sst/elements/firefly/Makefile.am
- src/sst/elements/hermes/Makefile.am
- src/sst/elements/thornhill/Makefile.am
- src/sst/elements/zodiac/Makefile.am
Firefly, hermes, thornhill do not have test directories and should not register the test dir path.
zodiac uses the non-standard test (should be tests) directory, changing registration to point to the correct path.
> Fix test directories registration for 4 elements

- Makefile.am
Change the EXTRA_DIST in the makefile to distribute everything in the config directory.  This should fix the Balar issue in detecting gpgpusim
> Change the EXTRA_DIST in the makefile to distribute config directory.

- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/interfaces/portControl.cc
- src/sst/elements/merlin/router.h
The routers default to 2 VNs if the number is not specified.  This
should work for most simple simulations.  New features have made it
too complex to continue to support autoconfiguring based on the
requested VNs from the endpoints.  The endpoints will still need to
request the number of VNs they want so that VN remapping will
continue to work.
> Removed the VN autoconfigure functionality from hr_router.

- src/sst/elements/ember/pyember.py
- src/sst/elements/merlin/interfaces/linkControl.cc
- src/sst/elements/merlin/interfaces/linkControl.h
- src/sst/elements/merlin/pymerlin-base.py
- src/sst/elements/merlin/router.h
Removed checkerboarding from LinkControl as it was no longer a
useful feature and made it difficult to do vn remapping efficiently.
Fixed vn remapping to work in the case of mapping multiple
requested VNs into the same physical VN.  Also should be a
little more efficient.
Added code to pyember.py to support mapping of message types to
VNs.  Also somewhat improved the setting of default parameters.
> Several related changes to merlin and ember.

- config/sst_check_gpgpusim.m4
Fix for https://github.com/sstsimulator/sst-elements/issues/1464
Note that this is not a complete fix -- this only works for gcc-7+. If an older version of gcc is configured with --with-gcc-major-version-only, the configure will still fail.
> Fix for gcc version check

- config/sst_check_gpgpusim.m4
Moves to sed and --version instead of dumpversion, which is finicky.
> Fix gcc Version Check in GPGPUSim Macro

- src/sst/elements/merlin/pymerlin-base.py
Re-enabled _createPrefixedParams in _SubAttributeManager.  It only got moved to TemplateBase in the last code restructuring.
> Merlin python prefixed params fix

- src/sst/elements/serrano/Makefile.am
Addresses a build error for Serrano's test examples.
```
make[10]: *** No rule to make target 'tests/graph/sum.graph', needed by 'distdir-am'.  Stop.
```
> Fix Build Error for Serrano Test Examples

- src/sst/elements/ariel/arielmemmgr_simple.cc
- src/sst/elements/ariel/arielmemmgr_simple.h
Adds printing of page translation tables for Ariel Simple Memory Manager when verbosity levels >= 16. This will print a lot of translation information to the screen (which will result in large outputs and much slower performance).
> Adds Printing of Ariel Page Translation Table (Ariel Simple Memory Manager) when using Verbose Debugging

- src/sst/elements/CramSim/tests/testsuite_default_CramSim.py
- src/sst/elements/Samba/tests/testsuite_default_Samba.py
- src/sst/elements/cacheTracer/tests/testsuite_default_cacheTracer.py
- src/sst/elements/cassini/tests/testsuite_default_cassini_prefetch.py
- src/sst/elements/ember/tests/testsuite_default_embernightly.py
- src/sst/elements/ember/tests/testsuite_default_qos.py
- src/sst/elements/miranda/tests/testsuite_default_miranda.py
Core Test frameworks modified the compare_diff routines and provided a get diff results function.  This PR resolves the issues some tests had when running a 2 rank + 2 thread test.
> Improve compare diff testing

- src/sst/elements/vanadis/Makefile.am
Remove reference to Python files in Vanadis `Makefile.am`. This has caused failure in `make dist` testing.
> Fix missing Python files for make dist in Vanadis

- src/sst/elements/vanadis/decoder/vdecoder.h
- src/sst/elements/vanadis/os/node/vnodeoswritevh.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vnodeoshandler.h
- src/sst/elements/vanadis/vanadis.cc
- Improves quality of clock_gettime64 calls to be accurate (write back of seconds is now 8 bytes, not 4 which causes incorrect values to be used).
- Improves simulation performance by guarding `snprintf` calls in performance critical parts of the pipeline model
- Fixes up some defaults for decoder performance
> Several Fixes for Vanadis Emulated OS Calls that Improve Quality of Benchmark Timing Output

- src/sst/elements/merlin/Makefile.am
- src/sst/elements/merlin/pymerlin-base.py
- src/sst/elements/merlin/pymerlin-endpoint.py
- src/sst/elements/merlin/test/simple_patterns/empty.cc
- src/sst/elements/merlin/test/simple_patterns/empty.h
- src/sst/elements/merlin/test/simple_patterns/incast.cc
- src/sst/elements/merlin/test/simple_patterns/incast.h
Added incast and empty patterns. In the system object, unallocated nodes will automatically use the EmptyJob class.
> Merlin: Added incast and empty patterns

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/inst/vadd.h
- src/sst/elements/vanadis/inst/vaddi.h
- src/sst/elements/vanadis/inst/vandi.h
- src/sst/elements/vanadis/inst/vdecodefaultinst.h
- src/sst/elements/vanadis/inst/vdivmod.h
- src/sst/elements/vanadis/inst/vfp2fp.h
- src/sst/elements/vanadis/inst/vfpconv.h
- src/sst/elements/vanadis/inst/vfpdiv.h
- src/sst/elements/vanadis/inst/vfpmul.h
- src/sst/elements/vanadis/inst/vfpsub.h
- src/sst/elements/vanadis/inst/vgpr2fp.h
- src/sst/elements/vanadis/inst/vjl.h
- src/sst/elements/vanadis/inst/vjlr.h
- src/sst/elements/vanadis/inst/vjr.h
- src/sst/elements/vanadis/inst/vjump.h
- src/sst/elements/vanadis/inst/vscmpi.h
- src/sst/elements/vanadis/inst/vslli.h
- src/sst/elements/vanadis/inst/vsra.h
- src/sst/elements/vanadis/inst/vsrai.h
- src/sst/elements/vanadis/lsq/vlsq.h
- src/sst/elements/vanadis/lsq/vlsqseq.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/util/vsignx.h
- src/sst/elements/vanadis/vanadis.cc
Provides several updates
- Immediate extract and shift support is now outlined into a function
- Basic support to process RT_SIGSETMASK, but this may still produce incorrect masks in certain circumstances
- Supports enhanced print outs for LSQ in `printStatus()` (SIGUSR2 calls)
- Tidy up logical and arithmetic shift instructions when sign-extension is required
- Fixes potential bug in 32b register mode for shifts when attempting to write back a 64b value without sign extension
- General tidy up for printStatus() calls in main Vanadis core
> Update for Vanadis to correct potential bugs in immediate offsets for branches and jumps 

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/inst/vinstall.h
- src/sst/elements/vanadis/inst/vtrunc.h
Fixes an bug in decoding of `SLL` by zero instructions that should create a truncation operation.
> Fix Shift Left by Zero Immediate Decode Bug in Vanadis

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/inst/vbfp.h
- src/sst/elements/vanadis/inst/vfpscmp.h
Provides fixes for:
- Branch on true for floating-point compare (previously always evaluates to false)
- Fixes `Makefile.am` missing truncation instructions
- Cleans instruction code string floating-point compare to make more readable
> Fixes for Vanadis for Branch on Floating Point True and Makefile.am

- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/velf/velfinfo.h
Adds support to detect dynamically linked executables and fatal if found. Vanadis only supported statically linked executables currently. Issue #1584.
> Vanadis - Detect and Error on Dynamic Linked Executables

- src/sst/elements/ariel/Makefile.am
Adding 2 missing files needed for balar in the Ariel distribution.
> Fixing ariel makefile dist for balar

- src/sst/elements/cassini/tests/testsuite_default_cassini_prefetch.py
Cassini tests with ranks=2 and threads=2 take slightly longer than the allotted test timeout, bumping the timeout up a bit.
> Increase test timeout for cassini tests

- src/sst/elements/vanadis/inst/vfp2fp.h
- src/sst/elements/vanadis/inst/vfp2gpr.h
- src/sst/elements/vanadis/inst/vfpadd.h
- src/sst/elements/vanadis/inst/vfpconv.h
- src/sst/elements/vanadis/inst/vfpdiv.h
- src/sst/elements/vanadis/inst/vfpmul.h
- src/sst/elements/vanadis/inst/vfpscmp.h
- src/sst/elements/vanadis/inst/vfpsub.h
- src/sst/elements/vanadis/inst/vgpr2fp.h
- src/sst/elements/vanadis/inst/vload.h
- src/sst/elements/vanadis/inst/vstore.h
- src/sst/elements/vanadis/lsq/vlsqseq.h
- src/sst/elements/vanadis/tools/tracediff/tracediff.cc
FIx up compiler warnings reported by @allevin. These occur in GCC but should be harmless as the enums should include all options.
> Initial vanadis

- src/sst/elements/vanadis/inst/vmulsplit.h
- src/sst/elements/vanadis/os/node/vnodeoswritevh.h
- src/sst/elements/vanadis/os/vnodeoshandler.h
Fixes compiler warnings for mostly formatting issues in Vanadis when compiling on macOS.
> Fix Vanadis Compiler Warning on MacOS

- src/sst/elements/memHierarchy/scratchpad.cc
**Problem:**
After a processor sends a ScratchGet command to the scratchpad and receives a response from the main memory,  the data from the main memory is not written to the scratchpad rightly because of the wrong way of initializing the data vector. 
**Solution:**
The original way of initializing the data vector,
`std::vector<uint8_t> data(response->getPayload()[payloadOffset],response->getPayload()[payloadOffset+size]);` may not copy the response's payload to the data vector correctly.  Because this  form of constructor is matched to the second form, the **fill constructor** about constructing a vector in the [cpp reference about vector](https://www.cplusplus.com/reference/vector/vector/vector/).
So I modified it to match the third one, the **range constructor** in the [cpp reference …
> fix a bug about writing data to scratchpad

- config/sst_check_llvm_config.m4
Added flag, --with-llvm-config to build system
-llvm-config must be in user path
-calls llvm-config to add CFLAGS, CXXFLAGS, and LDFLAGS
> Add llvm-config Check to Builder

- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_dirnoncacheable.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_diropenMP.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_noncacheable.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_openMP.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dir3LevelSweep.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweep.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweepB.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweepI.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_openMP.py
Fix for issue #1650 
Added checks for PIN on all memH sweep and openMP tests.  These tests are special case tests that are normally only run on a Linux machine with PIN installed.  They are not normally run on other platforms.
> Adding skips to openMP and sweep tests if PIN is not loaded

- src/sst/elements/simpleSimulation/Makefile.am
Addresses issue found in #1683 
Fixes this issue by including reference files in distribution (via `Makefile.am`).
> Include reference files for simpleSimulation in Distribution

- src/sst/elements/ember/test/emberLoad.py
The additional comma (,) meant you could not call the "debug" modelOption of emberLoad.py with "--debug=1", as the option was not recognized because of the additional comma.
> Remove comma (,) from getopt string for option "debug="

- src/sst/elements/firefly/nic.cc
Disclaimer: I do not know how to test if this change is correct, but:
By chance, when working on extending Firefly, I found this.
`Nic::dmaSend` uses the same callback as `Nic::pioSend` even though there is a matching callback in the `Nic::notify*Done` member functions. This does feel unintentional and looks like a bug.
Thank for looking into it. It does not affect me, but possibly someone else.
> SST::Fifrefly::Nic::dmaSend uses incorrect notify*Done callback

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/velf/velfinfo.h
Perform a check for the endianness of the executable during ELF load. If this is not a supported type, then fatal. 
This is reported by @calewis in PR #1693.
> Vanadis add check for Endian in ELF Format Checks

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/velf/velfinfo.h
Addresses comments in : #1693 and PR: #1699
Provide endian checking capability for MIPSEL in Vanadis executable loaders.
> Switch Endian checks in ELF to Enum

- src/sst/elements/memHierarchy/membackend/flagMemBackendConvertor.h
Changed FlagMemBackendConvertor to use itself as the subcomp API instead of MemBackendConvertor.
> memH ELI fix for FlagMemBackendConvertor

- src/sst/elements/VaultSimC/app.cpp
- src/sst/elements/VaultSimC/memReqEvent.h
Fixes unneeded include in VaultSimC which would import the ELI definition. The result is the memHierarchy loads can fail when dynamically loaded because VaultSimC is also not loaded.
The definitions are not needed and so this removes the load time failure.
> Removes unneeded include in VaultSimC that imports the ELI definition

- src/sst/elements/Opal/Opal.cc
Fix a type warning in an output statement. Generates a warning during compile.
> Fix warning in Opal relating to type in output statement

- src/sst/elements/memHierarchy/coherencemgr/coherenceController.cc
CoherenceController::recordMiss(...) was on the hot path, specifically
the std::map::find. Old code made 2 calls to find() for each func,
I switched it to make 1 call each time, seems to have 10-15% speedup on
skylake benchmark.
---
* These branches are …
> Optimized memHierarchy:CoherenceController

- src/sst/elements/memHierarchy/membackend/backing.h
- src/sst/elements/memHierarchy/memoryCacheController.h
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/memHierarchy/scratchpad.h
The 'memory_file' parameter description on some components in
memH suggests support for 'storing resulting state' through
to the specified file. This fix mmap's as MAP_SHARED, and ensures munmap/close gets called.
> memH: fix mmap based backing to memory_file

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vjl.h
- Adds support for additional RVC (compressed) instructions
- Remove `JAL` micro-op trap when instruction target is not 4-byte aligned (this is MIPSO32 specific)
> Adds support for additional RVC instructions in Vanadis

- src/sst/elements/memHierarchy/memNICBase.h
- src/sst/elements/memHierarchy/memNICFour.cc
For some otherwise reasonable specification on sources/destination lists -- which
are interpreted as watchlists to process incoming 'imre' -- if an imre happens to match
in the source-list, the destinationEndpoint info in the nic is never updated even if
this imre were also a match in the destionation-list, leading to an incomplete discovery process.
> memH: fix; memNIC sources/destinations params

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vjl.h
- src/sst/elements/vanadis/inst/vjump.h
- src/sst/elements/vanadis/inst/vload.h
- src/sst/elements/vanadis/inst/vpcaddi.h
- src/sst/elements/vanadis/lsq/vlsqseq.h
- src/sst/elements/vanadis/tests/basic_vanadis.py
- src/sst/elements/vanadis/vanadis.cc
- Improves micro-op print out/debugging generation in Vanadis
- Allows debug print outs for load payloads returning to the LSQ
- Configures 64b aux-vector for RISCV ELF binaries (this results in major bugs if still at 32b)
> Improve Debugging Prints for Micro-ops in Vanadis

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- Fixes bugs in 64b initial stack layouts (including auxiliary vectors) for RISC-V
- Refactors 32b immediate decodes for shifts and add operations
> Fixes Initial Stack Layout Bugs for RISC-V 64b 

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vinstall.h
- src/sst/elements/vanadis/inst/vstorecond.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- src/sst/elements/vanadis/tests/basic_vanadis.py
Update includes:
- Specific micro-op for store-conditional which allows response success register to be provided as a parameter
- Provides initial RISCV OS Handler
- Switches MIPS and RISCV decoder to new SC decode/generation sequence
- Provides capability in `basic_vanadis.py` to specify OS by ISA type
> Update Vanadis to Overhaul Store-Conditionals and Initial Implementation of RISCV OS Handler

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vsrai.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- Fixes RVC immediate decode errors for several instructions
- Adds `ECALL` / `SYSCALL` for `set_tid`
- Adds `ECALL`/ `SYSCALL` for `exit_group`
- Fixes up decoder generate for RVC `EBREAK` instruction
- Fixes incorrect immediate generate for `SRAI` instruction in RV32 and RV64
> Fix RVC Decoder Bugs for Immediates in Vanadis

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vbcmp.h
- src/sst/elements/vanadis/inst/vbcmpi.h
- src/sst/elements/vanadis/inst/vload.h
- src/sst/elements/vanadis/inst/vstore.h
- src/sst/elements/vanadis/inst/vxori.h
- src/sst/elements/vanadis/vanadis.cc
Fixes several issues on Vanadis:
- Fixes 32b instruction operands issue (when using 64b registers)
- Adds additional print outs for loads and stores to help debugging
- Adds prints for speculation target addresses at retirement
- Fixes register ordering problem in RVC `AND`, `OR` etc
> Fix for Decoder Bugs on Vanadis

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/inst/vjlr.h
- src/sst/elements/vanadis/os/callev/voscallaccessev.h
- src/sst/elements/vanadis/os/callev/voscallbrk.h
- src/sst/elements/vanadis/os/callev/voscallclose.h
- src/sst/elements/vanadis/os/callev/voscallexitgrp.h
- src/sst/elements/vanadis/os/callev/voscallfstat.h
- src/sst/elements/vanadis/os/callev/voscallgettime64.h
- src/sst/elements/vanadis/os/callev/voscallioctl.h
- src/sst/elements/vanadis/os/callev/voscallmmap.h
- src/sst/elements/vanadis/os/callev/voscallopen.h
- src/sst/elements/vanadis/os/callev/voscallopenat.h
- src/sst/elements/vanadis/os/callev/voscallread.h
- src/sst/elements/vanadis/os/callev/voscallreadlink.h
- src/sst/elements/vanadis/os/callev/voscallsta.h
- src/sst/elements/vanadis/os/callev/voscalluname.h
- src/sst/elements/vanadis/os/callev/voscallunmap.h
- src/sst/elements/vanadis/os/callev/voscallwrite.h
- src/sst/elements/vanadis/os/callev/voscallwritev.h
- src/sst/elements/vanadis/os/callev/vosinitbrk.h
- src/sst/elements/vanadis/os/node/vnodeoswritevh.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vnodeoshandler.h
- src/sst/elements/vanadis/os/vosbittype.h
- src/sst/elements/vanadis/os/voscallev.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- Propagates 64b support to emulated OS handlers in Vanadis
- Removes 4B alignment check for `JLR` micro-op jump targets, need to support 2B/16b targets for RISCV/RVC
> Propagate 64b support to emulated OS in Vanadis

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vinstall.h
- src/sst/elements/vanadis/inst/vmod.h
- src/sst/elements/vanadis/inst/vslli.h
- src/sst/elements/vanadis/inst/vsrli.h
Makes following changes:
- Improve print/debugging output for `SLLI`, `SLRI` and `W` variants
- Adds support for basic arithmetic over 64b values in decoder
- Creates modulo micro-op for RISCV in 64b (including signed/unsigned) because split `DIV/MOD` operation is for MIPSO32
> Add Modulo Micro-Op and Improve Decoder Generation for RISC-V Vanadis

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vadd.h
- src/sst/elements/vanadis/inst/vsub.h
- src/sst/elements/vanadis/tests/small/basic-math/Makefile
- src/sst/elements/vanadis/tests/small/basic-math/sqrt-double.c
- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/vanadis.h
- Provides a parameter to the RISCV decoder to decide if code should halt on decode faults (used for debugging), default no. This should help the `STOP` condition in #1767 
- Improves print out for debugging ADD and SUB micro-ops (shows their data size widths)
> Provide Option in RISCV Decoder to Halt on Decode Fault

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vfpscmp.h
- src/sst/elements/vanadis/inst/vfpsignlogic.h
- src/sst/elements/vanadis/inst/vinstall.h
- src/sst/elements/vanadis/inst/vmipsfpscmp.h
- src/sst/elements/vanadis/tests/testsuite_default_vanadis.py
- Switches FP compare and set implementation to be a MIPS-specific micro-op (too different from other implementations)
- Increase timeouts for testing
> Switch FP Compare for MIPS to Special Micro-Op in Vanadis

- src/sst/elements/Samba/Makefile.am
- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/PageTableWalker.h
- src/sst/elements/Samba/Samba.h
- src/sst/elements/Samba/SimpleTLB.cc
- src/sst/elements/Samba/SimpleTLB.h
- src/sst/elements/Samba/TLBUnit.cc
- src/sst/elements/Samba/TLBUnit.h
- src/sst/elements/Samba/TLBhierarchy.cc
- src/sst/elements/Samba/TLBhierarchy.h
- src/sst/elements/Samba/tests/simpletlb_test.py
Adds Samba.SimpleTLB component. (Currently more of a trivial-virtual-memory-remapper than a TLB; the name is aspirational)
Can be placed between CPU and caches in the usual way using ports `high_network` and `low_network`, where it should transparently allow memory accesses to pass by default.
Can specify a fixed region of memory to remap elsewhere with the following params:
```
"fixed_mapping_va_start": "0x0",                  
"fixed_mapping_pa_start": "0xF000000",            
"fixed_mapping_len": "128MB",            
```
Any request into the specified virtual address region get re-mapped, all others pass through unchanged.
NOTE: All the actual code additions are in SimpleTLB.cc and SimpleTLB.h
Edits to PageTableWalker.\*, TLBUnit.\*, TLBhierarchy.\*, Samba.\* are me going through and …
> Added component Samba.SimpleTLB

- src/sst/elements/vanadis/decoder/vdecoder.h
- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vfp2fp.h
- src/sst/elements/vanadis/inst/vfp2gpr.h
- src/sst/elements/vanadis/inst/vfpadd.h
- src/sst/elements/vanadis/inst/vfpconv.h
- src/sst/elements/vanadis/inst/vfpdiv.h
- src/sst/elements/vanadis/inst/vfpinst.h
- src/sst/elements/vanadis/inst/vfpmul.h
- src/sst/elements/vanadis/inst/vfpscmp.h
- src/sst/elements/vanadis/inst/vfpsignlogic.h
- src/sst/elements/vanadis/inst/vfpsub.h
- src/sst/elements/vanadis/inst/vgpr2fp.h
- src/sst/elements/vanadis/inst/vinst.h
- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/vanadis.h
- src/sst/elements/vanadis/vfpflags.h
Provides support for floating-point flags/exceptions in the Vanadis pipeline:
- Enables overflow, underflow, zero flags to be set
- Enable div-by-zero flags for divide operations
- Flag update on instruction retire is default operation
- Supports rounding mode set/read but this does not affect calculation operations in current design
> Enable Floating-Point Flags in Vanadis

- src/sst/elements/merlin/topology/fattree.cc
Setting the routing algorithm for a Fat Tree uses the parameter "routing_alg" but this is only checked for a list of algorithms, it was checking for the parameter name "algorithm" when one routing algorithm was set but this is not valid. 
It may be worth swapping the name of this parameter to match the Dragonfly parameters which use the parameter name "algorithm".
> Fixed incorrect parameter name for routing algorithm

- src/sst/elements/rdmaNic/tests/app/rdma/msg.out.gold
- src/sst/elements/vanadis/os/memmgr/vmemmgr.h
- src/sst/elements/vanadis/os/vnodeoshandler.h
Fix OPEN and OPENAT syscall handler so that the first memory access of file path is cache aligned.
Enable runtime configuration of debug verbosity of VanadisMemoryManager.
> Minor Vanadis I/O Fixes

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
Minor fix for Vanadis which fixes 'override' keyword in RISCV decoder.
> Fix override error in RISCV decoder

- src/sst/elements/vanadis/os/vnodeoshandler.h
- src/sst/elements/vanadis/tests/basic_vanadis.py
Vanadis was failing because of a function not returning a value.
> Fix vanadis 

- src/sst/elements/mercury/Makefile.am
Mercury bug fix: Use proper asm for linux/osx
> Use proper asm for linux/osx

- src/sst/elements/CramSim/c_AddressHasher.cpp
- src/sst/elements/GNA/GNA.cc
- src/sst/elements/GNA/GNA.h
- src/sst/elements/GNA/neuron.h
- src/sst/elements/GNA/sts.cc
- src/sst/elements/GNA/sts.h
- src/sst/elements/memHierarchy/membackend/HBMpagedMultiBackend.cc
- src/sst/elements/memHierarchy/membackend/pagedMultiBackend.h
- Changes several uses of `uint` over to `uint32_t` to fix issues identified in bug #1929.
> Fix use of uint instead of uint32_t in several components

- src/sst/elements/mercury/Makefile.am
Older automake (e.g. 1.13.4) don't include a libtool tag for assembly files (.S) and, due to some other libtool oddities, libtool can't infer that it should use either c or c++ mode (both work actually).
This fix is a hack that happens to work -- just stick --tag=CXX in front of every call to libtool by adding it to AM_LIBTOOLFLAGS. Since we're always compiling c++ files we get lucky and this works without breaking anything else.
I don't like it, but it works.
> Fix automake for Mercury

- src/sst/elements/vanadis/datastruct/cqueue.h
- src/sst/elements/vanadis/datastruct/vcache.h
Tweak circular queue and standard cache data structures to improve performance by a small amount in long running Vanadis simulations.
> Tweak Data Structures to Improve Performance in Vanadis

- src/sst/elements/vanadis/datastruct/vcache.h
std::list will not work with const iters in c++98...and it looks like this isn't completely implemented in c++11 in gcc-4.8.2
> Fix for gcc 4.2 std::list

- src/sst/elements/memHierarchy/memNIC.cc
@tomhaber submitted a bug (Issue #1916) regarding the `memHierarchy.memNIC` coupling to `merlin.linkcontrol`.  The bug is associated with the correct naming conventions for the `merlin.linkcontrol` `input_buf_size` and `output_buf_size`.  This is a very simple fix to inject the correct names in the subcomponent parameter setup for this particular subcomponent.  
Version tested: sst-elements-devel (2022.12.16); sst-core-devel (2022.12.16)
> fixing merlin linkcontrol parameters for memHierarchy.memNIC

- src/sst/elements/vanadis/decoder/vdecoder.h
- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
Add support to the RISCV decoder for RDCYCLE instruction.
> add rdcycle assembly instruction support

- src/sst/elements/ariel/frontend/pin3/pin3frontend.cc
Fixes #2070. 
This PR adds code to kill the child process in the `Pin3Frontend::finish()` method, so that the child process does not keep running after the simulation has ended.
> Kill child process in finish phase if it is still running

- src/sst/elements/vanadis/os/include/virtMemMap.h
- src/sst/elements/vanadis/os/syscall/mprotect.cc
mprotect was not properly splitting a memory region
> Vanadis: fix mprotect bug

- src/sst/elements/vanadis/os/vnodeos.cc
When a MMIO page was faulted in the offset into the region was not being corrected calculated.
> offset of MMIO device was wrong

- src/sst/elements/rdmaNic/rdmaNic.h
- src/sst/elements/rdmaNic/rdmaNicHostInterface.h
- src/sst/elements/rdmaNic/tests/app/rdma/Makefile
- src/sst/elements/rdmaNic/tests/app/rdma/incast-v2.c
- src/sst/elements/rdmaNic/tests/app/rdma/incast.c
- src/sst/elements/rdmaNic/tests/app/rdma/include/base.h
- src/sst/elements/rdmaNic/tests/app/rdma/msg.out.gold
- src/sst/elements/rdmaNic/tests/app/rdma/msg.stdout-node0.cpu0.os.gold
- src/sst/elements/rdmaNic/tests/app/rdma/msg.stdout-node1.cpu0.os.gold
- src/sst/elements/rdmaNic/tests/app/rdma/src/base.c
- src/sst/elements/rdmaNic/tests/app/rdma/src/rdma.c
- src/sst/elements/rdmaNic/tests/app/rdma/write.c
- src/sst/elements/rdmaNic/tests/vanadisBlock.py
Make the RDMA NIC work with both MIPS and RISCV. Make RISCV the default.
> RDMA NIC fix for RISCV

- src/sst/elements/vanadis/os/vnodeos.cc
When an exitgroup happens there is a race condition where a syscall from an hardware thread could be processed by the OS after it terminated the process.
> Vanadis: Fix syscall to dead process

- src/sst/elements/ember/libs/emberMpiLib.h
Require nonnull request for isend in EmberMpiLib. Addresses issue #2162
> Require nonnull request for isend in EmberMpiLib

- src/sst/elements/merlin/merlin.cc
- src/sst/elements/merlin/pymerlin-base.py
- Bug in getting attributes for in TemplateBase when there is a passthrough object
- Issue with Bridge not being in ELI in libmerlin
> Fixed minor bugs in merlin:

- src/sst/elements/memHierarchy/memNIC.cc
- src/sst/elements/memHierarchy/memNICBase.h
- src/sst/elements/memHierarchy/memNICFour.cc
- src/sst/elements/memHierarchy/memNetBridge.cc
- src/sst/elements/memHierarchy/networkMemInspector.cc
- src/sst/elements/opal/opalMemNIC.cc
This PR fixes a memory leak in MemH. When MemRtrEvent wraps an event and gets deleted, it does not delete the wrapped event. This PR adds a destructor to ensure the wrapped event gets deleted and changes the wrapped object to be protected instead of public. It also includes functions for interacting with the event.
- `takeEvent()` returns the pointer to the event and sets the pointer to `nullptr`. 
- `inspectEvent()` returns the pointer but does not set the pointer to `nullptr`
- `putEvent()` is used to set the value of the Event
> Fix MemH MemRtrEvent memory leak

- src/sst/elements/ember/Makefile.am
OTF2 was not linked to when compiling the OTF2 Trace motif. 
This fixes it, not the best solution as it should be handled with the auto tools but this will work.
> Fixed issue with calling OTF2 functions from Ember getting unresolved names

- src/sst/elements/ariel/frontend/pin3/fesimple.cc
gcc 12.3.0 complains about a use after free in pin3/fesimple.cc. This removes that undefined behavior.
> Fix use after free

- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/membackend/memBackendConvertor.cc
I've actually seen these stats take a good chunk of SST's runtime in our simulations, so this should help.
> Add to stats more efficiently in various turnClockOn() functions

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/mpi/motifs/emberTrafficGen.cc
- src/sst/elements/ember/mpi/motifs/emberhotspots.cc
- src/sst/elements/ember/mpi/motifs/emberhotspots.h
Ember: add HotSpots motif
This is an improved version of the hot spots extended pattern in the TrafficGen motif.
I will eventually remove the similar functionality from the TrafficGen motif, but I will hold off on that as external users may be depending on it at the moment.
> Ember: add HotSpots motif

- src/sst/elements/firefly/pyfirefly.py
The maxRecvMachineQsize parameter was misspelled in the BasicNicConfiguration python object, so the parameter could never be set since it didn't match the spelling in the C++ model.
> Fix issue with mispelled parameter name in pyfirefly

- src/sst/elements/merlin/Makefile.am
- src/sst/elements/merlin/interfaces/pymerlin-interface.py
- src/sst/elements/merlin/pymerlin-base.py
- src/sst/elements/merlin/pymerlin-endpoint.py
- src/sst/elements/merlin/router.h
- src/sst/elements/merlin/tests/dragon_128_test_deferred.py
- src/sst/elements/merlin/tests/refFiles/test_merlin_dragon_128_test_deferred.out
- src/sst/elements/merlin/tests/testsuite_default_merlin.py
- src/sst/elements/merlin/topology/dragonfly.cc
- src/sst/elements/merlin/topology/dragonfly.h
- src/sst/elements/merlin/topology/pymerlin-topo-dragonfly.py
- src/sst/elements/merlin/topology/pymerlin-topo-fattree.py
- src/sst/elements/merlin/topology/pymerlin-topo-hyperx.py
- src/sst/elements/merlin/topology/pymerlin-topo-mesh.py
- src/sst/elements/merlin/topology/pymerlin-topo-polarfly.py
- src/sst/elements/merlin/topology/pymerlin-topo-polarstar.py
Changed merlin python topology builders so that they call pushNamePrefix() with the network name and added deferred build to System object so you can build without endpoints and get the links later to connect.
> Merlin python updates

- src/sst/elements/iris/sumi/collective_actor.cc
- src/sst/elements/mask-mpi/mpi_api_comm.cc
- src/sst/elements/mask-mpi/mpi_api_send_recv.cc
- src/sst/elements/mask-mpi/mpi_api_wait.cc
- src/sst/elements/mask-mpi/mpi_protocol/rendezvous_rdma.cc
- src/sst/elements/mercury/common/component.cc
- src/sst/elements/mercury/common/component.h
- src/sst/elements/mercury/common/event_link.cc
Fix compiler warnings in mercury and related elements
> Mercury: fix warnings

- .github/workflows/ci.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
Part of https://github.com/sstsimulator/sst-core/issues/1053 and https://github.com/sstsimulator/sst-elements/issues/2329.
Pre-commit doesn't do much here because of the agreement that there is no enforcement of clang-format on elements.  It is still useful for future lints and the main CI file is still required for when building/testing is later added.
> GitHub Actions infrastructure for pre-commit checks

- src/sst/elements/memHierarchy/tests/testsuite_default_memHierarchy_memHA.py
`testsuite_default_memHierarchy_memHA.py` regexes need to be updated to use raw strings.
Closes #2350
> memHierarchy_memHA: convert RE to raw string

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/os/syscall/exit.cc
- src/sst/elements/vanadis/os/vnodeos.cc
- src/sst/elements/vanadis/os/vnodeos.h
- src/sst/elements/vanadis/os/vphysmemmanager.h
- src/sst/elements/vanadis/vanadis.cc
Most of the warnings are related to format specifiers.
> cleanup various vanadis warnings

- src/sst/elements/mercury/common/serializable.h
Fix Mercury headers to keep in sync with changes to core serialization.
> Mercury: fix serialization headers

- src/sst/elements/iris/sumi/allgather.h
- src/sst/elements/iris/sumi/alltoall.h
- src/sst/elements/iris/sumi/sim_transport.cc
- src/sst/elements/mask-mpi/Makefile.am
- src/sst/elements/mask-mpi/tests/allgather.cc
- src/sst/elements/mask-mpi/tests/refFiles/test_allgather.out
- src/sst/elements/mask-mpi/tests/refFiles/test_alltoall.out
- src/sst/elements/mask-mpi/tests/test_allgather.py
- src/sst/elements/mask-mpi/tests/testsuite_default_mask_mpi.py
Remove unnecessary builder/factory for some collective implementations, which enables those collectives.
> mask-mpi: add missing collectives

- src/sst/elements/kingsley/linkControl.cc
- src/sst/elements/kingsley/noc_mesh.cc
- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/memNICBase.h
Simulations using memHierarchy and kingsley components (e.g. memHierarchy/tests/testMemoryCache.py and testPrefetchParameters.py) sometimes have events that are never deleted. Many of these are in initialization, but some were during execution and caused the memory pool usage to grow during simulation execution.  This PR addresses undeleted events in the following:
- prefetch handling in cacheController.cc clock_tick()
- memNICBase.h nicInit
- credit events in kingsley noc_mesh.cc noc_mesh::init
- kingsley LinkControl::init
There are still some remaining undeleted events but many fewer and they mostly appear to be in initialization where they don't cause increasing memorypool usage with simulation time.
> Resolve some memorypool  undeleted events

- src/sst/elements/merlin/bridge.h
pymerlin expects to override a SimpleNetwork subcomponent with its own network subcomponent (e.g., LinkControl). When using a Bridge, this subcomponent is ignored and link initialization crashes on SST::Link::sendUntimedData when trying to access a null rtr object. This patch extends the Bridge component to use the user subcomponent if set and if not then fall back to using an anonymous subcomponent as before.
> merlin/bridge: load user subcomponent for networkIF

- src/sst/elements/miranda/mirandaCPU.cc
- src/sst/elements/miranda/mirandaGenerator.h
For my simulation, approximately 15-20% of CPU time is spent resolving one dynamic_cast in miranda. This dynamic cast does not appear to be necessary because mirandaCPU dispatches GeneratorRequests based on the request's operation.
This patch replaces the dynamic_cast with an operation check and adds an assertion on the MemoryOpRequest's operation type. The assertion ensures a MemoryOpRequest is either READ or WRITE to avoid potential incorrect static_cast'ing into CustomOpRequests.
> miranda: check request operation instead of using dynamic_cast

- src/sst/elements/merlin/interfaces/linkControl.cc
LinkControl::send allocates a RtrEvent to first compute the number of flits needed to send a request. If there's not enough credits, the method returns early without deleting the RtrEvent object and leaks its memory. This patch deletes the object before returning to fix the leak.
> merlin/linkcontrol: fix memory leak on insufficient send credits

- src/sst/elements/ariel/tests/testsuite_default_Ariel.py
- src/sst/elements/ariel/tests/testsuite_mpi_Ariel.py
- src/sst/elements/cramSim/tests/test_txntrace.py
- src/sst/elements/ember/test/generateNidListQOS.py
- src/sst/elements/ember/tests/testsuite_default_ember_otf2.py
- src/sst/elements/gensa/tests/OutputParser.py
- src/sst/elements/gensa/tests/testsuite_default_gensa.py
- src/sst/elements/memHierarchy/tests/testsuite_default_memHierarchy_memHSieve.py
- src/sst/elements/mercury/tests/testsuite_default_hg.py
- src/sst/elements/prospero/tests/testsuite_default_prospero.py
This removes calls to test functions that were deprecated (https://github.com/sstsimulator/sst-core/pull/1136, https://github.com/sstsimulator/sst-core/pull/1137, https://github.com/sstsimulator/sst-core/pull/1145) and fixes a few other warnings, particularly about unclosed files.
> Remove calls to deprecated Python test framework functions

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
This PR adds latency statistics to `ArielCore`s. It also changes the `ArielCore`s to use a `timeconverter` passed from the `ArielCPU`, instead of relying on default behavior.
> Add latency tracking to Ariel

- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_dirnoncacheable.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_diropenMP.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_noncacheable.py
- src/sst/elements/memHierarchy/tests/testsuite_openMP_memHierarchy_openMP.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dir3LevelSweep.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweep.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweepB.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_dirSweepI.py
- src/sst/elements/memHierarchy/tests/testsuite_sweep_memHierarchy_openMP.py
According to https://docs.python.org/3.9/library/unittest.html, `assertEquals` has been deprecated since at least Python 3.2, so this silences a lot of output in running these tests.
> unittest: replace assertEquals with assertEqual

- src/sst/elements/merlin/topology/pymerlin-topo-mesh.py
A simple fix for an apparent typo in the merlin topology script.
See also: https://github.com/sstsimulator/sst-elements/issues/2446
> Merlin: fix typo in pymerlin-topo-mesh script

- src/sst/elements/ember/mpi/motifs/emberotf2.cc
- src/sst/elements/ember/mpi/motifs/emberotf2.h
This change extends the OTF2 motif in Ember, so that it can read the global string definitions from an OTF2 trace into memory. String definitions (e.g., function names) are referenced in OTF2 event packets through stringRef ids. This change will allow Ember to interpret these references. There are also local (per rank) definitions in OTF2, but this change is concerned only with reading the global strings.
To avoid issues with potentially lots of string definitions in large trace files, the loading is disabled by default. To enable one has to set the readGlobalStringDefinitions config parameter:
...
ep = EmberMPIJob(0, topo.getNumNodes())
...
ep.addMotif("OTF2 tracePrefix=trace.otf2 readGlobalStringDefinitions=True")
....
> Ember: adds reading global string definitions from OTF2 traces

- src/sst/elements/messier/nvm_dimm.cc
- src/sst/elements/samba/tlb_unit.cc
This fixes a build error which was detected when compiling sst-elements with the STL debug option `-D_GLIBCXX_DEBUG`:
```
CXX      nvm_dimm.lo
../../../../../src/sst/elements/messier/nvm_dimm.cc: In member function 'void SST::MessierComponent::NVM_DIMM::schedule_delivery()':
../../../../../src/sst/elements/messier/nvm_dimm.cc:223:31: error: no match for 'operator=' (operand types are 'std::__debug::map<SST::MessierComponent::NVM_Request*, long long int>::iterator' and 'std::__debug::map<SST::MessierComponent::NVM_Request*, long long int, SST::MessierComponent::NVM_DIMM::NVMReqPtrCompare>::iterator')
223 |     st_1 = ready_at_NVM.begin();
|                               ^
(similar error for en_1)
CXX      tlb_unit.lo
../../../../../src/sst/elements/samba/tlb_unit.cc: In member function …
```
> Fix iterator type mismatches caused by the std::map comparison functor being left out

- src/sst/elements/merlin/target_generator/uniform.h
- src/sst/elements/merlin/trafficgen/trafficgen.h
In Merlin, `MersenneRNG` is used without the `SST::RNG::` namespace specifier. This happened to work because of a bug in SST Core which imported all of `SST::RNG` into the global namespace.
Other parts of SST Elements use the correct full name `SST::RNG::MersenneRNG`.
If a SST name in global namespace is desired for `MersenneRNG`, such as `SSTMersenneRNG` (similar to `SSTGaussianDistribution` and `SSTUniformDistribution`), it can be added to SST Core.
> In Merlin, use SST:RNG::MersenneRNG instead of bare MersenneRNG

- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/api/arielapi.c
- src/sst/elements/ariel/configure.m4
- src/sst/elements/ariel/mpi/Makefile.am
As part of building Ariel, `libarielapi.so` is built. This PR installs the library with the rest of SST, in the `$pkglibdir` directory. This will make it easier for external programs that depend on this library to find it. The header is also installed with the rest of the Ariel headers and a small bugfix for arielapi.c is included.
> Install libarielapi.so as part of installing sst-elements

- src/sst/elements/simpleElementExample/basicSubComponent_subcomponent.h
This fixes the subcomponent for issue [(sstsimulator/sst-core#1228)](https://github.com/sstsimulator/sst-core/issues/1228). It adds the required constructor and macro for each subcomponent so that the test can be run with checkpointing enabled. I went ahead with this PR so the code could be reviewed as I'm basing other subcomponent checkpointing models on this code.
> Subcomponent fix for checkpointing

- configure.ac
Add include guard to sst_element_config.h.  Similar to sstsimulator/sst-core#1269
> Add include guard to sst_element_config.h

- src/sst/elements/memHierarchy/memLink.h
- src/sst/elements/memHierarchy/memLinkBase.h
- src/sst/elements/shogun/shogun_nic.h
`UNUSED()` macro has no effect in function declarations which aren't definitions.
> remove unnecessary UNUSED() macros in declarations (not definitions)

- src/sst/elements/firefly/nic.h
- src/sst/elements/iris/sumi/message.h
- src/sst/elements/memHierarchy/membackend/timingTransaction.h
- src/sst/elements/memHierarchy/mshr.h
- src/sst/elements/rdmaNic/rdmaNic.h
- src/sst/elements/serrano/serrano.h
This adds `#include <list>` and a few other `#include`s which were missing in Elements because it depended on them being `#include`d by Core.
Core serialization is in the process of being refactored such that it does not explicitly depend on standard containers like `std::list` and instead works on any types with certain properties, like having a `value_type` defined, and having `begin()`, `end()` and `push_back()` methods available.
A thorough review of Elements (and Core) should be done at some point, to `#include` the necessary headers used in each subcomponent, and not rely on them being `#include`d somewhere else.
@kpgriesser
> Add #include <list> to a bunch of headers

- src/sst/elements/ember/mpi/motifs/embersiriustrace.cc
- src/sst/elements/iris/libfabric/prov/sumi/src/sumi_eq.cc
[scan-build](https://clang.llvm.org/docs/analyzer/user-docs/CommandLineUsage.html#scan-build) detected a few memory size mismatches on the subset of elements I was building.
> Static analysis detected memory allocation issues

- src/sst/elements/iris/sumi/sim_transport.cc
We `std::move(f)` on line 230.  According to the spec this leaves `f` in a valid but unspecified state.  On line 235 we call `f` which we should not be doing.
> Fix use_after_move

- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/coherencemgr/MESI_Inclusive.h
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.h
- src/sst/elements/memHierarchy/memLink.h
- src/sst/elements/memHierarchy/memNICFour.h
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/vanadis/inst/vadd.h
- src/sst/elements/vanadis/inst/vdiv.h
- src/sst/elements/vanadis/inst/vfence.h
- src/sst/elements/vanadis/inst/vfp2gpr.h
- src/sst/elements/vanadis/inst/vfpclass.h
- src/sst/elements/vanadis/inst/vfpconv.h
- src/sst/elements/vanadis/inst/vfpsqrt.h
- src/sst/elements/vanadis/inst/vgpr2fp.h
- src/sst/elements/vanadis/inst/vmin.h
- src/sst/elements/vanadis/inst/vnop.h
- src/sst/elements/vanadis/inst/vnor.h
- src/sst/elements/vanadis/inst/vor.h
- src/sst/elements/vanadis/inst/vori.h
- src/sst/elements/vanadis/inst/vpartialload.h
- src/sst/elements/vanadis/inst/vpartialstore.h
- src/sst/elements/vanadis/inst/vscmp.h
- src/sst/elements/vanadis/inst/vslli.h
- src/sst/elements/vanadis/inst/vstore.h
- src/sst/elements/vanadis/inst/vsyscall.h
- src/sst/elements/vanadis/inst/vxor.h
By the default build flags, Clang/LLVM prints warnings for overriden functions not marked `override`.
Remove trailing whitespace from `memHierarchy` `Makefile.am`.
> Add override to overriden functions to remove Clang warnings

- src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py
The core is changing the checkpoint index to start from 1 instead of 0.  Will need to reenable after that PR merges.
> Temporarily disable checkpoint test in SimpleElementExample

- src/sst/elements/mask-mpi/mpi_comm/mpi_comm_cart.h
- src/sst/elements/mask-mpi/tests/sendrecv.cc
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/vanadis/lsq/vbasiclsq.h
This fixes miscellaneous warnings found by Clang/LLVM using the default build's compiler flags.
@gvoskuilen In `memHierarchy/directoryController.cc`, a useless comparison looks like it should have been an assignment.
@jpkenny In `mask-mpi/mpi_comm/mpi_comm_cart.h`, there was an off-by-1 comparison of an array index. I fixed it and also flagged negative indices.
In `mask-mpi/tests/sendrecv.cc` and `memHierarchy/cacheFactory.cc`, variable-length array warnings were removed by making their dimension variables `const`.  (There are still other cases of VLAs in Elements which are non-`const` in size.)
In `vanadis/lsq/vbasiclsq.h`, redundant parentheses around a comparison were removed.
> fix misc warnings

- src/sst/elements/ember/tests/testsuite_default_ember_sweep.py
- src/sst/elements/memHierarchy/tests/testsuite_default_memHierarchy_memHA.py
- src/sst/elements/messier/tests/testsuite_default_Messier.py
- src/sst/elements/miranda/tests/testsuite_default_miranda.py
- src/sst/elements/prospero/tests/testsuite_default_prospero.py
- src/sst/elements/rdmaNic/tests/testsuite_default_rdmaNic.py
- src/sst/elements/samba/tests/testsuite_default_Samba.py
- src/sst/elements/vanadis/tests/testsuite_default_vanadis.py
- src/sst/elements/zodiac/test/testsuite_default_SiriusZodiacTrace.py
Including:
* EmberSweep
* miranda_randomgen
* vanadis_short_tests
This cuts the running time of `sst-test-elements` by ~20 minutes.
The tests are still there and will run during Nightly testing.
Depends on https://github.com/sstsimulator/sst-core/pull/1290
> Disable long running tests for non-Nightly tests

- configure.ac
- src/sst/elements/mask-mpi/mpi_api_type.cc
- src/sst/elements/mask-mpi/mpi_comm/mpi_comm_cart.cc
- src/sst/elements/zodiac/zsirius.cc
Similar to https://github.com/sstsimulator/sst-core/pull/1255
> Replace Variable Length Arrays with arrays allocated with std::make_unique

- src/sst/elements/mercury/tests/testsuite_default_hg.py
The Mercury test is currently non-deterministic and will sometimes fail on MT-2 / MT-4 platforms.  Disable them for now.
> Mercury: skip the test_testme() method

- src/sst/elements/mercury/common/thread_safe_int.h
- src/sst/elements/mercury/operating_system/process/app.cc
Lock `App::lockDlopen()` and raise the lock in `operator++()`.
This is possibly an incomplete list.  YMMV.
> Mercury: fix race condition

- src/sst/elements/vanadis/os/include/fdTable.h
There was a format mismatch in `scanf()` for `mode_t`, which is an `int` but was treated as a `short`.
```Diff
-        assert( 1 == fscanf(fp,"mode: %hd\n", &mode) );
+        f = fscanf(fp,"mode: %d\n", &mode);
+        assert( 1 == f );
```
`<assert.h>` and `<stdint.h>` were not `#include`d.
Also, `assert()` conditions should not have side effects because `assert()` can be disabled with `-DNDEBUG`.
@mjleven
> Fix scanf() format mismatch; move side effects outside of assert()
