sstsimulator/sst-elements

- VaultSimC/Vault.cpp
- VaultSimC/Vault.h
- VaultSimC/VaultSimC.cpp
- VaultSimC/VaultSimC.h
- VaultSimC/globals.h
- VaultSimC/libVaultSimGen.cpp
- VaultSimC/logicLayer.cpp
- VaultSimC/logicLayer.h
- Non-HMC Read and Write stat added
- Logic-Layer stat added
- logicLayer init function removed, since we are not using it
- removed all memBuffers in VaultSim, also init function since we are not processing command now
- general comments
- link delays removed from code
> VaultSim, LogicLayer code cleanup + Stat

- scheduler/DragonflyMachine.cc
- scheduler/DragonflyMachine.h
- scheduler/Factory.cc
- scheduler/Factory.h
- scheduler/Machine.h
- scheduler/Makefile.am
- scheduler/README
- scheduler/allocMappers/NearestAllocMapper.cc
- scheduler/allocMappers/NearestAllocMapper.h
- scheduler/schedComponent.cc
The additional feature will be used with ember & merlin to study dragonfly topologies
> scheduler support for dragonfly topology

- ember/test/emberLoad.py
Fixes typo in EmberLoad reported by @shavvn.
> Fix for issue #62 reported in Ember test scripts

- memHierarchy/cacheController.h
- memHierarchy/cacheFactory.cc
- memHierarchy/directoryController.cc
- memHierarchy/directoryController.h
- memHierarchy/libmemHierarchy.cc
- memHierarchy/mshr.h
> Mh Fix for issue #29, add mshr occupancy statistic to caches and directory

- ariel/arielcore.cc
- ariel/arielcore.h
- ariel/arielmemmgr.cc
- ariel/arielmemmgr.h
Improves performance a small bit on Ariel.
> Switch Ariel over to use unordered_map to reduce insertion times

- memHierarchy/IncoherentController.cc
- memHierarchy/L1CoherenceController.cc
- memHierarchy/L1CoherenceController.h
- memHierarchy/L1IncoherentController.cc
- memHierarchy/L1IncoherentController.h
- memHierarchy/MESICoherenceController.cc
- memHierarchy/MESICoherenceController.h
- memHierarchy/MESIInternalDirectory.cc
- memHierarchy/MESIInternalDirectory.h
- memHierarchy/bus.cc
- memHierarchy/cacheArray.h
- memHierarchy/cacheController.cc
- memHierarchy/cacheController.h
- memHierarchy/cacheEventProcessing.cc
- memHierarchy/coherenceControllers.h
- memHierarchy/directoryController.cc
- memHierarchy/dmaEngine.cc
- memHierarchy/mshr.cc
Block cache lines for the duration of a cache access to force accesses to the same cache line to serialize.
Also added ifdefs around debug output
> Mh fix timing

- ember/Makefile.am
- ember/ember.cc
- ember/mpi/motifs/emberrandomgen.cc
- ember/mpi/motifs/emberrandomgen.h
Random traffic pattern for Ember.
> Randomized Traffic Pattern for Ember

- ariel/app/env/Makefile
- ariel/app/env/env.c
Add an environment printing application so we can check what gets put into Ariel.
> Add an Environment Print Application for Ariel

- ember/mpi/motifs/embersiriustrace.cc
- ember/mpi/motifs/embersiriustrace.h
- ember/sirius/include/sirius/siriusglobals.h
- ember/sirius/libsirius/libsirius.cc
Fixes an issue with request mapping in Ember when NULL requests may be provided.
> Fixes an issue with Request Mapping in Ember

- ember/test/emberLoad.py
fixed bug dealing with undefined network_inspector
Now it checks to make sure network_inspector param is defined.
> fixed bug dealing with undefined network_inspector

- zodiac/test/allreduce/allreduce.py
- zodiac/zodiac.cc
Zodiac merge into devel. Mike's last PR was into master which is not currently allowed in the workflow.
> Zodiac Merge into Devel

- ember/emberengine.cc
- ember/mpi/embermpigen.cc
Changes EmberEngine and MPI Generator Base Class to use new Parameter Interface in SST v6.0.
> Changes Ember to use new parameter interface for SST v6.0

- firefly/functionSM.cc
- firefly/rangeLatMod.h
- firefly/scaleLatMod.h
Change FireFly to use the new Params Interface for SST v6.0
> Change FireFly to use the new Params Interface for SST v6.0

- VaultSimC/cpu.cpp
> removed deprecated params

- ariel/arielcore.cc
- firefly/libfirefly.cc
- firefly/nic.cc
- m5C/m5lib.cpp
- memHierarchy/libmemHierarchy.cc
- memHierarchy/membackend/pagedMultiBackend.cc
- memHierarchy/membackend/simpleMemBackend.cc
- merlin/merlin.cc
- merlin/reorderLinkControl.cc
- merlin/test/bisection/bisection_test.cc
- merlin/test/nic.cc
- merlin/test/pt2pt/pt2pt_test.cc
- merlin/test/simple_patterns/shift.cc
- merlin/topology/dragonfly.cc
- merlin/topology/dragonfly2.cc
- merlin/topology/mesh.cc
- merlin/topology/torus.cc
- pyproto/pyproto.cc
- scheduler/nodeComponent.cc
- simpleElementExample/simpleComponent.cc
- simpleElementExample/simpleMessageGeneratorComponent.cc
DeclareSerializable is not longer needed
> Remove DeclareSerializable from all elements

- ariel/arielcpu.cc
Switch over Ariel CPU loading `Params` to the new template-based interface.
> Switch over to new Params interface for Ariel

- prospero/proscpu.cc
Change Prospero over to use new `Params` interface
> Change Prospero over to use new Params interface

- ariel/arielcore.cc
- ariel/arielgzbintracegen.h
- ariel/arieltexttracegen.h
> Fix params for Ariel tracers

- ariel/arielcpu.cc
Fix Additional Params in Ariel
> Fix Additional Params in Ariel

- prospero/Makefile.am
Set Correct Paths for Prospero Trace Tool in Makefile.am
> Set Correct Paths for Prospero Trace Tool in Makefile.am

- cassini/addrHistogrammer.cc
- cassini/dmaengine.cc
- cassini/nbprefetch.cc
- cassini/strideprefetch.cc
Fix Cassini to use new Params API
> Fix Cassini to use new Params API

- miranda/mirandaCPU.cc
Miranda - Change Parameters to new API
> Miranda - Change Parameters to new API

- ember/mpi/motifs/emberallpingpong.cc
Fix for Ember is the rank count is odd.
> Ember AllPingPong Fix for Odd Node Count

- src/sst/elements/miranda/miranda.cc
- src/sst/elements/miranda/mirandaCPU.cc
- src/sst/elements/miranda/mirandaCPU.h
- src/sst/elements/miranda/mirandaEvent.h
Support External Event-Driven Generators on Miranda
> Support External Event-Driven Generators on Miranda

- autogen.sh
Add DIST element libraries to Makefile variable list
> Add DIST element libraries to Makefile variable list

- src/sst/elements/memHierarchy/membackend/pagedMultiBackend.h
> memH: Fix paged multi backend error

- src/sst/elements/ariel/frontend/simple/fesimple.cc
Use compressed backtrace if possible. Also find fortran ariel api routine names.
> Ariel: Add compressed backtrace to fesimple

- .gitignore
- config/.gitignore
- src/.gitignore
Add some .gitignores to clean up elements
> Cleanup with some .gitignores

- src/sst/elements/firefly/nicRecvMachine.cc
- src/sst/elements/firefly/nicSendMachine.cc
- src/sst/elements/firefly/nicSendMachine.h
> Fix Firefly  NIC receive processing

- src/sst/elements/ember/embercomputeev.h
- src/sst/elements/ember/emberdetailedcomputeev.h
- src/sst/elements/ember/embergen.cc
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/mpi/emberMPIEvent.h
- src/sst/elements/ember/mpi/embermpigen.cc
- src/sst/elements/ember/mpi/embermpigen.h
> Move ember compute events out of ember/mpi

- src/sst/elements/thornhill/Makefile.am
---
`1` Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements
`2` Verify that Source branch is up to date with the devel branch of sst-elements
`3` After submitting your Pull Request:
* Pull Requests from forks will not be automatically merged into the devel branch.
* …
> missing header in Makefile.am

- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/networkConfig.py
Definitions of hosts_per_group, numGroups, and numNodes are corrected.
> Network config fix: Corrected computation of numNodes in DragonflyInfo()

- src/sst/elements/qsimComponent/qsimComponent.cc
- src/sst/elements/qsimComponent/qsimComponent.h
Serialization and event code changes apparently were not migrated to qsim.
> Fix qsim serialization and event code

- src/sst/elements/qsimComponent/Makefile.am
- src/sst/elements/qsimComponent/patches/qsim-0.2.1-fileOpenCheck.patch
- src/sst/elements/qsimComponent/qsimComponent.cc
- src/sst/elements/savannah/arbitrator/savfifoarb.h
- src/sst/elements/scheduler/Factory.cc
- src/sst/elements/scheduler/InputParser.cc
- src/sst/elements/scheduler/faultInjectionComponent.cc
- src/sst/elements/scheduler/nodeComponent.cc
- src/sst/elements/scheduler/schedComponent.cc
Fix param warnings on:
qsim
scheduler
savannah 
Also copied the patch file for qsim (that resides in sst-sqe, but is not available to the field).
> Fix param warnings and add patch file for qsim

- Makefile.am
Add the Support Files (Caps Files) to the distribution.
> Add support files to the extra-dist

- src/sst/elements/ember/run/configurations/defaultParams.py
> need default params

- src/sst/elements/memHierarchy/directoryController.cc
> memH: Fix to caching for directory controller

- src/sst/elements/scheduler/schedComponent.cc
> Clean up scheduler warnings

- src/sst/elements/ariel/frontend/simple/fesimple.cc
- src/sst/elements/memHierarchy/Sieve/broadcastShim.cc
- src/sst/elements/memHierarchy/Sieve/sieveController.cc
- src/sst/elements/memHierarchy/Sieve/sieveFactory.cc
- src/sst/elements/memHierarchy/bus.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/membackend/simpleDRAMBackend.cc
- src/sst/elements/memHierarchy/memoryController.cc
1. Remove some compile warnings on Mac
2. Fix Ariel fesimple bug in ariel_output_stats (wasn't thread-safe)
> Mh warnings

- src/sst/elements/scheduler/Mesh3DMachine.cc
- src/sst/elements/scheduler/taskMappers/TopoMapper.cc
Add needed header files that were probably includes indirectly through the serialization files that have been removed.
> Add necessary header files.

- configure.ac
Fix reporting errors for out-of-source builds in SST elements.
> Fix reporting errors for out-of-source builds

- .gitignore
- src/sst/elements/ariel/.gitignore
- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/ariel_shmem.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/frontend/simple/fesimple.cc
- src/sst/elements/prospero/.gitignore
This branch is dependent upon the sst-core / bjmoor/interprocess branch.
Manual testing was performed multiple times on Ubuntu, sst-test, and MacOSX platforms suing the bjmoor/interproces brances of sst-core and sst-elements along with the devel branch of sst-sqe.  All tests have passed.
The Pull request will be manually merged to avoid synchronization issues with the autotester.
> Merge Bjmoor/interprocess branch to sst-elements

- .gitignore
- src/sst/elements/ariel/.gitignore
- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/ariel_shmem.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/frontend/simple/fesimple.cc
- src/sst/elements/prospero/.gitignore
> Merge Bjmoor/interprocess branch to sst-elements (#413)

- src/sst/elements/ariel/ariel_shmem.h
> Simple cleanups

- src/sst/elements/cassini/strideprefetch.cc
> Fix memory leak in stride prefetcher

- src/sst/elements/scheduler/schedComponent.cc
Identified by @bjmoor in the development of destructors in SST-Core.
> Fixes destructor issue in Scheduler due to Uninitialized Variable

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/libmemHierarchy.cc
- src/sst/elements/memHierarchy/membackend/delayBuffer.cc
- src/sst/elements/memHierarchy/membackend/delayBuffer.h
> memH: Added delay buffer membackend to add latency to memory requests

- src/sst/elements/firefly/ctrlMsgProcessQueuesState.h
> fix using already freed structure

- src/sst/elements/hermes/hermes.h
> fix valgrind error

- src/sst/elements/ember/run/configurations/testFile
- src/sst/elements/ember/run/script/emberLoadCmd.py
- src/sst/elements/ember/run/script/emberLoadFile.py
I was looking at the code in /ember/run/ but wasn't able to run it due to various bugs there... Here's my fix and I'm wondering if this is a deprecated folder since there's a lot of similar code in /ember/test/ that works.
> Fix ember bugs

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/ember.cc
- src/sst/elements/ember/mpi/motifs/emberdetailedstream.cc
- src/sst/elements/ember/mpi/motifs/emberdetailedstream.h
- src/sst/elements/ember/run/configurations/3LevelModel.py
- src/sst/elements/ember/run/configurations/3LevelModelParams.py
- src/sst/elements/ember/run/configurations/basicDetailedModelParams.py
- src/sst/elements/ember/run/configurations/detailedStreamSim.py
- src/sst/elements/ember/run/configurations/sandyBridgeModel.py
- src/sst/elements/ember/run/configurations/sandyBridgeModelParams.py
- src/sst/elements/ember/run/configurations/testCmd
- src/sst/elements/ember/run/configurations/testFile
- src/sst/elements/ember/run/configurations/testJob
- src/sst/elements/ember/run/configurations/testStreamCmd
- src/sst/elements/ember/run/lib/emberLoadBase.py
- src/sst/elements/ember/run/lib/jobInfo.py
- src/sst/elements/ember/run/lib/loadUtils.py
- src/sst/elements/ember/run/script/emberLoadCmd.py
- src/sst/elements/miranda/generators/copygen.h
- src/sst/elements/miranda/generators/streambench.cc
- src/sst/elements/miranda/mirandaCPU.cc
> Mjleven/emberDetailed 

- src/sst/elements/miranda/Makefile.am
- src/sst/elements/miranda/miranda.cc
- src/sst/elements/miranda/mirandaCPU.cc
- src/sst/elements/miranda/mirandaCPU.h
- src/sst/elements/miranda/mirandaMemMgr.h
Has small improvement in predictive accuracy at larger scale simulations. General support for page mapping in Miranda, initially just LINEAR (default) and RANDOMIZED (new).
> Support for Physical Page Randomization Scheme in Miranda

- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielmemmgr.cc
- src/sst/elements/ariel/arielmemmgr.h
- src/sst/elements/ariel/libariel.cc
Improves page randomization in Ariel via the memory manager.
> Add Page Randomization to Ariel

- src/sst/elements/ariel/api/Makefile
- src/sst/elements/ariel/api/arielapi.c
- src/sst/elements/ariel/api/arielapi.h
Adds a build of the Ariel client API to the Ariel toolchain.
> Basic Ariel API Library

- src/sst/elements/ariel/frontend/simple/examples/stream/ariel_ivb.py
- src/sst/elements/ariel/frontend/simple/examples/stream/ariel_snb.py
Change Sandy Bridge test input to produce common output across Linux platforms.
> No backing

- src/sst/elements/CramSim/CramSim.cpp
- src/sst/elements/CramSim/README
> Cramsim changes to fix name reporting in sst-info

- src/sst/elements/CramSim/c_BankInfo.cpp
> initialize uninitialized Variable

- src/sst/elements/miranda/tests/gupsgen.py
Adds GUPS Generator test to Miranda
> Miranda add GUPS Generator Test

- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.h
Comments provided by @jleidel in PR #481 are below. This PR applies the changes to a clean checkout to pass modified tests present in the SQE framework.
Adding parameter parsing for power measurement feature strings.  Each device component power metric can be individually tuned in an SST python script.  Adding CMC (custom memory cube) support.  CMC libraries can now be loaded directly from the SST python script.
This pull request adds the following parameters for goblinHMCBackend: 
- link_phy_power : float
- link_local_route_power : float
- link_remote_route_power : float
- xbar_rqst_slot_power : float
- xbar_rsp_slot_power : float
- xbar_route_extern_power : float
- vault_rqst_slot_power : float
- vault_rsp_slot_power : float
- vault_ctrl_power : float
- row_access_power : float
- …
> Apply GoblinHMCSim Changes from @jleidel (PR #481) to Clean Branch

- src/sst/elements/ember/embermotiflog.cc
- src/sst/elements/ember/embermotiflog.h
Attempts to lock updates to the Ember log file construction.
> Fix Ember Thread Safety for Log File Handling

- src/sst/elements/VaultSimC/Makefile.am
Add memReqEvent.h to VaultSim Makefile.am
> Update makefile.am for makedist

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/libmemHierarchy.cc
- src/sst/elements/memHierarchy/membackend/timingAddrMapper.h
- src/sst/elements/memHierarchy/membackend/timingDRAMBackend.cc
- src/sst/elements/memHierarchy/membackend/timingDRAMBackend.h
- src/sst/elements/memHierarchy/membackend/timingPagePolicy.h
- src/sst/elements/memHierarchy/membackend/timingTransaction.h
> add timingDRAM backend

- src/sst/elements/memHierarchy/membackend/delayBuffer.cc
- src/sst/elements/memHierarchy/membackend/delayBuffer.h
- src/sst/elements/memHierarchy/membackend/dramSimBackend.cc
- src/sst/elements/memHierarchy/membackend/flashSimBackend.cc
- src/sst/elements/memHierarchy/membackend/goblinHMCBackend.cc
- src/sst/elements/memHierarchy/membackend/hmcMemBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/hmcMemBackendConvertor.h
- src/sst/elements/memHierarchy/membackend/hybridSimBackend.cc
- src/sst/elements/memHierarchy/membackend/memBackend.h
- src/sst/elements/memHierarchy/membackend/memBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/pagedMultiBackend.cc
- src/sst/elements/memHierarchy/membackend/ramulatorBackend.cc
- src/sst/elements/memHierarchy/membackend/requestReorderByRow.cc
- src/sst/elements/memHierarchy/membackend/requestReorderByRow.h
- src/sst/elements/memHierarchy/membackend/requestReorderSimple.cc
- src/sst/elements/memHierarchy/membackend/requestReorderSimple.h
- src/sst/elements/memHierarchy/membackend/simpleDRAMBackend.cc
- src/sst/elements/memHierarchy/membackend/simpleMemBackend.cc
- src/sst/elements/memHierarchy/membackend/simpleMemBackendConvertor.cc
- src/sst/elements/memHierarchy/membackend/simpleMemBackendConvertor.h
- src/sst/elements/memHierarchy/membackend/timingDRAMBackend.h
- src/sst/elements/memHierarchy/membackend/vaultSimBackend.cc
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/memHierarchy/util.h
> support "stacked" backends

- src/sst/elements/memHierarchy/Sieve/tests/.gitignore
- src/sst/elements/prospero/tests/array/.gitignore
- src/sst/elements/zodiac/test/allreduce/.gitignore
Insert three additional .gitignore files
> Three .gitignores

- src/sst/elements/CramSim/Makefile.am
- src/sst/elements/Samba/Makefile.am
Add files needed for make-dist in Samba and one in CramSim
> Samba make dist

- src/sst/elements/CramSim/Makefile.am
New attempt at CramSim Makefile.am for MakeDist.
This pull request will not test MakeDist, only that nothing else is broken by the change
> Rest of cs

- src/sst/elements/CramSim/Makefile.am
> One more file to Makefile.am

- src/sst/elements/memHierarchy/cacheEventProcessing.cc
- src/sst/elements/memHierarchy/mshr.cc
- src/sst/elements/memHierarchy/mshr.h
- src/sst/elements/merlin/linkControl.cc
Fixes packet_latency discrepancy in single/multi-thread and cacheFlush-2.py failure.
> Mh test fixes

- src/sst/elements/Messier/Makefile.am
- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/Messier/WriteBuffer.h
Fixing the Makefile.am again, with other edits on NVM_DIMM.cc
** removing a deleted header from Makefile.am
---
* If testing passes, the source branch will be automatically merged …
> Fixing the Makefile.am again, with other edits on NVM_DIMM.cc

- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/memHierarchy/membackend/MessierBackend.cc
Fixing some write buffer heuristic ---
* Pull Requests from forks will not be automatically …
> Fixing some write buffer heuristic

- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/Messier/NVM_DIMM.h
Adding FCFS + prioritizing row buffer hits, clean up and code re-organization
* Pull Requests …
> Messier cleanup

- src/sst/elements/memHierarchy/Sieve/tests/refFiles/test_memHSieve.out
Copy in the Reference file for memHSieve to the elements tree.
> Pickup missing subtree

- src/sst/elements/chdlComponent/tests/refFiles/test_chdlComponent.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_with_dramsim.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_with_dramsim_binary.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_with_dramsim_compressed.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_with_dramsim_text.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_wo_dramsim.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_wo_dramsim_binary.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_wo_dramsim_compressed.out
- src/sst/elements/prospero/tests/refFiles/test_prospero_wo_dramsim_text.out
Prospero and CHDL reference files to Elements
> Try Again with prospero and chdl

- src/sst/elements/firefly/nicRecvMachine.cc
- src/sst/elements/firefly/nicRecvMachine.h
> was deleting an event too soon

- src/sst/elements/miranda/miranda.cc
- src/sst/elements/miranda/mirandaCPU.cc
- src/sst/elements/miranda/tests/test_subcomp.py
- src/sst/elements/simpleElementExample/Makefile.am
- src/sst/elements/simpleElementExample/simpleElementExample.cc
- src/sst/elements/simpleElementExample/simpleSubComponent.cc
- src/sst/elements/simpleElementExample/simpleSubComponent.h
- src/sst/elements/simpleElementExample/tests/test_simpleSubComponent.py
Examples of how to use the new-style subcomponents.
> Examples of new-style subcomponent

- src/sst/elements/Messier/tests/gupsgen_2RANKS.py
- src/sst/elements/Messier/tests/gupsgen_fastNVM.py
- src/sst/elements/Messier/tests/stencil3dbench_messier.py
- src/sst/elements/Messier/tests/streambench_messier.py
> New tests for Messier

- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/Messier/NVM_Params.h
- src/sst/elements/Messier/WriteBuffer.cc
- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/TLBUnit.cc
- src/sst/elements/Samba/TLBhierarchy.h
> Removing warnings

- src/sst/elements/ariel/arieltexttracegen.h
I think this is the last missing include.  ( @feldergast @nmhamster )
> Add missing include

- src/sst/elements/ariel/arielmemmgr_malloc.cc
Fixes compile warnings in the Ariel element.
> Fix Ariel Compile Warnings for SST 7.0 Release

- src/sst/elements/Messier/NVM_DIMM.cc
> A Fix for a bug

- LICENSE
Change `LICENSE` file over to new details reflecting Sandia's change in management.
> Change LICENSE to have NTESS funding statement

- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/TLBUnit.cc
> Fixed bugs

- src/sst/elements/Messier/Bank.h
- src/sst/elements/Messier/Cache.h
- src/sst/elements/Messier/Makefile.am
- src/sst/elements/Messier/Messier.cc
- src/sst/elements/Messier/Messier.h
- src/sst/elements/Messier/Messier_Event.h
- src/sst/elements/Messier/NVM_DIMM.cc
- src/sst/elements/Messier/NVM_DIMM.h
- src/sst/elements/Messier/NVM_Params.h
- src/sst/elements/Messier/NVM_Request.h
- src/sst/elements/Messier/Rank.h
- src/sst/elements/Messier/WriteBuffer.cc
- src/sst/elements/Messier/WriteBuffer.h
- src/sst/elements/Messier/libMessier.cpp
- src/sst/elements/Messier/memReqEvent.h
> New messier (Cleanups,copyright, new messier)

- src/sst/elements/merlin/bridge.h
- src/sst/elements/merlin/linkControl.h
- src/sst/elements/merlin/reorderLinkControl.h
- src/sst/elements/merlin/test/bisection/bisection_test.h
- src/sst/elements/merlin/test/nic.h
- src/sst/elements/merlin/test/pt2pt/pt2pt_test.h
- src/sst/elements/merlin/test/route_test/route_test.h
- src/sst/elements/merlin/test/simple_patterns/shift.h
- src/sst/elements/merlin/topology/dragonfly.h
- src/sst/elements/merlin/topology/dragonfly2.h
- src/sst/elements/merlin/topology/mesh.h
- src/sst/elements/merlin/topology/torus.h
- src/sst/elements/merlin/trafficgen/trafficgen.h
- src/sst/elements/simpleElementExample/simpleClockerComponent.h
- src/sst/elements/simpleElementExample/simpleComponent.h
- src/sst/elements/simpleElementExample/simpleDistribComponent.h
- src/sst/elements/simpleElementExample/simpleLookupTableComponent.h
- src/sst/elements/simpleElementExample/simpleMessageGeneratorComponent.h
- src/sst/elements/simpleElementExample/simpleRNGComponent.h
- src/sst/elements/simpleElementExample/simpleStatisticsComponent.h
- src/sst/elements/simpleElementExample/simpleSubComponent.h
- src/sst/elements/simpleElementExample/simpleTracerComponent.h
> Moved all calls to new ELI macros to public section of class declaration

- configure.ac
> change makedist to use tar-pax instead of tar-ustar

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/libariel.cc
Adds a statistic to count read and write request sizes in Ariel.
> Statistic to Histogram Read and Write Request Sizes in Ariel

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/libariel.cc
Adds a cycle counter to each Ariel core.
> Add Cycle Counter to Ariel Core

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/libariel.cc
Adding max number of instructions parameter to ariel. Note that this is by default 0, and simply ignored unless set explicitly.
---
* If testing passes, the source branch will be …
> Adding max instructions parameter to Ariel

- src/sst/elements/firefly/ctrlMsgCommReq.h
- src/sst/elements/firefly/ctrlMsgMemory.h
- src/sst/elements/firefly/ctrlMsgMemoryBase.h
- src/sst/elements/firefly/ctrlMsgProcessQueuesState.cc
- src/sst/elements/firefly/ctrlMsgTiming.h
- src/sst/elements/firefly/ctrlMsgTimingBase.h
- src/sst/elements/firefly/ctrlMsgWaitReq.h
> Cleanup Firefly message protocol

- src/sst/elements/firefly/Makefile.am
- src/sst/elements/firefly/ctrlMsg.cc
- src/sst/elements/firefly/ctrlMsg.h
- src/sst/elements/firefly/ctrlMsgMemory.h
- src/sst/elements/firefly/ctrlMsgMemoryBase.h
- src/sst/elements/firefly/ctrlMsgProcessQueuesState.cc
- src/sst/elements/firefly/ctrlMsgProcessQueuesState.h
- src/sst/elements/firefly/ctrlMsgTiming.h
- src/sst/elements/firefly/ctrlMsgTimingBase.h
- src/sst/elements/firefly/ctrlMsgWaitReq.h
- src/sst/elements/firefly/ctrlMsgXXX.cc
- src/sst/elements/firefly/ctrlMsgXXX.h
- src/sst/elements/firefly/loopBack.cc
- src/sst/elements/firefly/loopBack.h
There is no functional code change. Just code reorganization.
> Cleanup the message passing protocol code

- src/sst/elements/ariel/arielcore.cc
Modifying the instruction count place in Ariel, so it also counts the no-ops.
---
* Pull Requests …
> Modifying instruction count

- src/sst/elements/miranda/generators/singlestream.cc
- src/sst/elements/miranda/generators/singlestream.h
Fix for https://github.com/sstsimulator/sst-elements/issues/706
> Fix for issue 706

- src/sst/elements/simpleElementExample/simpleSubComponent.h
> Fix minor typos

- src/sst/elements/ariel/api/Makefile
Changed Makefile in PIN API to create both shared and static libraries.
> Adding Static Library to PIN API

- src/sst/elements/memHierarchy/membackend/HBMpagedMultiBackend.cc
- src/sst/elements/memHierarchy/membackend/hybridSimBackend.cc
- src/sst/elements/memHierarchy/membackend/hybridSimBackend.h
> memH: Fix to backend clock() calls

- src/sst/elements/ember/Makefile.am
Header file required for Make Dist added to Makefile.am
> Add one file to Makefile.am

- src/sst/elements/CramSim/Makefile.am
- src/sst/elements/CramSim/README
- src/sst/elements/CramSim/ddr3.cfg
- src/sst/elements/CramSim/ddr4.cfg
- src/sst/elements/CramSim/ddr4_2400.cfg
- src/sst/elements/CramSim/ddr4_2667.cfg
- src/sst/elements/CramSim/ddr4_3200.cfg
- src/sst/elements/CramSim/ddr4_verimem.cfg
- src/sst/elements/CramSim/ddr4_verimem_openbank.cfg
- src/sst/elements/CramSim/test_system.cfg
- src/sst/elements/CramSim/tests/test_txngen.py
- src/sst/elements/CramSim/tests/test_txntrace.py
- src/sst/elements/CramSim/verify.cfg
Updated some minor details, as well as the Makefile.am for make-dist purposes.
> Updates to config files, README, and python configs

- src/sst/elements/CramSim/c_DeviceDriver.cpp
Initialization fix for valgrind.
> Fixed the uninitialized variable issue in c_DeviceDriver

- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/linkControl.cc
- src/sst/elements/merlin/linkControl.h
- src/sst/elements/merlin/portControl.cc
- src/sst/elements/merlin/portControl.h
- src/sst/elements/merlin/test/nic.cc
- src/sst/elements/merlin/test/nic.h
Add support for routing messages during complete() phase to merlin.
> Merlin add complete

- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/membackend/memBackend.h
- src/sst/elements/memHierarchy/membackend/memBackendConvertor.h
- src/sst/elements/memHierarchy/membackend/pagedMultiBackend.cc
- src/sst/elements/memHierarchy/membackend/timingDRAMBackend.cc
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/mshr.cc
- src/sst/elements/memHierarchy/testcpu/streamCPU.cc
And fix some compile warnings.
> memH: Fix problem with getRequestor return type. 

- src/sst/elements/memHierarchy/tests/refFiles/test_memHA_Flushes_2_MC.out
> New ref for memHA Flush_2 multi

- src/sst/elements/Opal/Opal.h
- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/PageTableWalker.h
- src/sst/elements/Samba/tests/gupsgen_mmu_opal.py
> Samba Initial Support for On-Demand Paging and Building Page Table

- src/sst/elements/Opal/Opal.cc
- src/sst/elements/Opal/Opal.h
- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/PageTableWalker.h
- src/sst/elements/Samba/Samba.cc
- src/sst/elements/Samba/Samba.h
- src/sst/elements/Samba/TLBhierarchy.h
- src/sst/elements/Samba/tests/gupsgen_mmu_opal.py
…bled, also Opal can set page fault latency
---
* If testing passes, the source branch will be automatically merged …
> Supports real page table walking + Emulating Page Fault (Physical Memory Allocation Request) latency

- src/sst/elements/Opal/Opal_Event.h
- src/sst/elements/Samba/PageTableWalker.cc
- src/sst/elements/Samba/Samba.cc
- src/sst/elements/Samba/TLBUnit.cc
- src/sst/elements/Samba/TLBhierarchy.cc
- src/sst/elements/Samba/TLBhierarchy.h
- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/libariel.cc
> Supporting Opal from Ariel, and overriding Ariel's physical addresses

- src/sst/elements/Opal/Opal.cc
- src/sst/elements/Opal/Opal.h
- src/sst/elements/Opal/Opal_Event.h
- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/frontend/simple/fesimple.cc
> Enable passing MLM allocation hints from ariel to Opal + Allowing mlm_malloc interception by default

- src/sst/elements/Opal/Opal.h
- src/sst/elements/Opal/Opal_Event.h
- src/sst/elements/ariel/ariel_shmem.h
- src/sst/elements/ariel/arielallocev.h
- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielevent.h
- src/sst/elements/ariel/frontend/simple/fesimple.cc
> Adding initial support for MLM mmap for a given file ID 

- src/sst/elements/firefly/nicShmem.cc
- src/sst/elements/firefly/nicShmemMove.cc
- src/sst/elements/firefly/nicShmemStream.cc
> Fix unbacked SHMEM operations

- src/sst/elements/Samba/PageTableWalker.cc
> Slight fix for Page Table Walker bookkeeping of mapped pages for fast fault detection

- src/sst/elements/ember/shmem/emberShmemGen.h
- src/sst/elements/ember/shmem/emberShmemGetEv.h
- src/sst/elements/ember/shmem/emberShmemPutEv.h
- src/sst/elements/ember/shmem/motifs/emberShmemGet.h
- src/sst/elements/ember/shmem/motifs/emberShmemPut.h
- src/sst/elements/firefly/hadesSHMEM.cc
- src/sst/elements/firefly/hadesSHMEM.h
- src/sst/elements/firefly/nicEvents.h
- src/sst/elements/firefly/nicShmem.cc
- src/sst/elements/firefly/nicShmem.h
- src/sst/elements/firefly/nicShmemStream.cc
- src/sst/elements/firefly/virtNic.cc
- src/sst/elements/firefly/virtNic.h
- src/sst/elements/hermes/shmemapi.h
> add put_nbi() and get_nbi()

- src/sst/elements/merlin/Makefile.am
> Include Merlin test input files in Release

- src/sst/elements/Opal/Opal.cc
- src/sst/elements/Opal/Opal.h
Memory allocation policies in Opal
> Opal is able to allocate memory with different allocation policies

- src/sst/elements/ember/test/emberLoad.py
> support setting individual parameters in ember load

- src/sst/elements/firefly/nic.cc
- src/sst/elements/firefly/nicRecvMachine.h
> remove dead code

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/emberengine.cc
- src/sst/elements/ember/emberengine.h
- src/sst/elements/ember/emberevent.h
- src/sst/elements/ember/embergen.cc
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/libs/emberLib.h
- src/sst/elements/ember/libs/misc.h
- src/sst/elements/ember/libs/miscEvents/emberGetNodeNumEvent.h
- src/sst/elements/ember/libs/miscEvents/emberMiscEvent.h
- src/sst/elements/ember/shmem/motifs/emberShmemAtomicInc.h
- src/sst/elements/ember/test/defaultParams.py
- src/sst/elements/firefly/Makefile.am
- src/sst/elements/firefly/hades.cc
- src/sst/elements/firefly/hades.h
- src/sst/elements/firefly/hadesMisc.h
- src/sst/elements/firefly/libfirefly.cc
- src/sst/elements/hermes/hermes.h
- src/sst/elements/hermes/miscapi.h
- src/sst/elements/hermes/shmemapi.h
- src/sst/elements/zodiac/zsirius.cc
> add a new Hermes API and support a new Motif library scheme

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/memHierarchyInterface.cc
- src/sst/elements/memHierarchy/memHierarchyInterface.h
> memH: Make interface a better base class

- src/sst/elements/firefly/nicShmem.cc
> fix non-blocking get ack

- src/sst/elements/firefly/Makefile.am
- src/sst/elements/firefly/memoryModel/busBridgeUnit.h
- src/sst/elements/firefly/memoryModel/cache.h
- src/sst/elements/firefly/memoryModel/cacheList.h
- src/sst/elements/firefly/memoryModel/cacheUnit.h
- src/sst/elements/firefly/memoryModel/loadUnit.h
- src/sst/elements/firefly/memoryModel/memReq.h
- src/sst/elements/firefly/memoryModel/simpleMemoryModel.h
- src/sst/elements/firefly/memoryModel/storeUnit.h
- src/sst/elements/firefly/memoryModel/thread.h
- src/sst/elements/firefly/memoryModel/tlb.h
- src/sst/elements/firefly/memoryModel/tlbUnit.h
- src/sst/elements/firefly/nic.cc
- src/sst/elements/firefly/nic.h
- src/sst/elements/firefly/nicRecvCtx.h
- src/sst/elements/firefly/nicRecvStream.cc
- src/sst/elements/firefly/nicSendMachine.cc
- src/sst/elements/firefly/nicSendMachine.h
Add a address cache (TLB) between the NIC ThreadUnits and the Load/Store Units.
> firefly NIC memoryModel TLB

- src/sst/elements/Opal/Opal.cc
- src/sst/elements/Opal/Opal.h
- src/sst/elements/Opal/Opal_Event.h
- src/sst/elements/Opal/mempool.cpp
- src/sst/elements/Opal/mempool.h
- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheEventProcessing.cc
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/directoryController.h
- src/sst/elements/memHierarchy/memLink.cc
- src/sst/elements/memHierarchy/memLinkBase.h
- src/sst/elements/memHierarchy/memNIC.cc
- src/sst/elements/memHierarchy/memNIC.h
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/memoryController.h
> Disagg amro

- src/sst/elements/ember/test/defaultParams.py
- src/sst/elements/ember/test/loadInfo.py
- src/sst/elements/ember/test/shmemLoadFile
- src/sst/elements/firefly/hadesSHMEM.cc
- src/sst/elements/firefly/hadesSHMEM.h
> fix emberload so loadfiles support SHMEM motifs

- src/sst/elements/Opal/Opal_Event.h
> Fix clang warning for Opal

- src/sst/elements/firefly/Makefile.am
Fix make dist Issues with FireFly resulting from missing files
> Fix make dist Issues with FireFly resulting from missing files

- src/sst/elements/ariel/arielcpu.cc
> long long to uint64_t

- src/sst/elements/ariel/frontend/simple/fesimple.cc
> fesimple.cc formatting

- src/sst/elements/ariel/api/arielapi.h
Not sure what fixed the issue but...it's fixed.
> Reverting 1045

- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/loadInfo.py
- src/sst/elements/ember/test/networkConfig.py
- src/sst/elements/scheduler/simulations/emberLoad.py
> add HyperX support to ember load scripts

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- Change pending_transaction_count to uint32_t to match maxPendingTransactions
- Fix spacing
- Change a 'delete' to 'delete[]'
> Ariel: some fixes

- src/sst/elements/cassini/addrHistogrammer.cc
- src/sst/elements/cassini/addrHistogrammer.h
- src/sst/elements/cassini/nbprefetch.cc
- src/sst/elements/cassini/nbprefetch.h
- src/sst/elements/cassini/palaprefetch.cc
- src/sst/elements/cassini/palaprefetch.h
- src/sst/elements/cassini/strideprefetch.cc
- src/sst/elements/cassini/strideprefetch.h
Working on new prefetcher and cleaning up source a bit.
> Cassini -- Cleaning up Source Tree

- src/sst/elements/ember/test/loadInfo.py
change loadInfo.py so it checks to see if the motif is from an external library
> support external motifs

- src/sst/elements/memHierarchy/Sieve/sieveFactory.cc
- src/sst/elements/memHierarchy/bus.cc
- src/sst/elements/memHierarchy/bus.h
- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.h
- src/sst/elements/memHierarchy/directoryController.cc
- src/sst/elements/memHierarchy/directoryController.h
Correcting typs in memH...Many of the parameters are typed as unsigned ints but were being cast as ints.
> Fixing Types

- src/sst/elements/firefly/nic.cc
- src/sst/elements/firefly/nic.h
- src/sst/elements/firefly/nicRecvMachine.h
- src/sst/elements/firefly/nicRecvStream.cc
- src/sst/elements/firefly/nicSendMachine.cc
> add statistics for the depth of the requested memory operation queue

- src/sst/elements/firefly/ctrlMsgProcessQueuesState.cc
- src/sst/elements/firefly/nic.cc
> fix compiler warnings

- src/sst/elements/ariel/frontend/simple/fesimple.cc
If ariel enabled -> return time ariel was enabled + elapsed sim time
If ariel not enabled -> return system time
> Ariel: Update gettimeofday/clock_gettime overrides

- src/sst/elements/ember/shmem/motifs/emberShmemFAM_Get.h
> fix FAM_Get

- src/sst/elements/firefly/memoryModel/memUnit.h
> a little optimization of memUnit

- src/sst/elements/firefly/Makefile.am
- src/sst/elements/firefly/memoryModel/simpleMemoryModel.h
- src/sst/elements/firefly/nic.cc
- src/sst/elements/firefly/nic.h
- src/sst/elements/firefly/nicSendMachine.cc
- src/sst/elements/firefly/nicSendMachine.h
- src/sst/elements/firefly/thingHeap.h
Use a priority Q as the source for outgoing packets.
> Change NIC send algorithm 

- src/sst/elements/scheduler/Factory.cc
- src/sst/elements/scheduler/Factory.h
- src/sst/elements/scheduler/Makefile.am
- src/sst/elements/scheduler/README
- src/sst/elements/scheduler/allocators/DflyHybridAllocator.cc
- src/sst/elements/scheduler/allocators/DflyHybridAllocator.h
- src/sst/elements/scheduler/allocators/DflyJokanovicAllocator.cc
- src/sst/elements/scheduler/allocators/DflyJokanovicAllocator.h
- src/sst/elements/scheduler/allocators/DflyRDGAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRDGAllocator.h
- src/sst/elements/scheduler/allocators/DflyRDRAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRDRAllocator.h
- src/sst/elements/scheduler/allocators/DflyRRNAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRRNAllocator.h
- src/sst/elements/scheduler/allocators/DflyRRRAllocator.cc
- src/sst/elements/scheduler/allocators/DflyRRRAllocator.h
- src/sst/elements/scheduler/allocators/DflySlurmAllocator.cc
- src/sst/elements/scheduler/allocators/DflySlurmAllocator.h
Add new allocation policies specific for simulating dragonfly topology system.
Descriptions of these policies are in sst-elements/src/sst/elements/scheduler/README.
These are works done at Boston University in collaboration with the Sandia National Laboratories,
and published in Y. Zhang, O. Tuncer, F. Kaplan, K. Olcoz, V. J. Leung and A. K. Coskun, "Level-Spread: A New Job Allocation Policy for Dragonfly Networks," 2018 IEEE International Parallel and Distributed Processing Symposium (IPDPS), Vancouver, BC, 2018, pp. 1123-1132.
Contact me or Vitus J. Leung for more information.
--- …
> Add new allocation policies for dragonfly topology system

- src/sst/elements/firefly/nic.h
- src/sst/elements/firefly/nicRecvCtx.cc
> fix bug where src stream number is not big enough

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/ember.cc
- src/sst/elements/ember/shmem/motifs/emberShmemFAM_Get2.h
- src/sst/elements/ember/shmem/motifs/emberShmemFAM_RandGet.h
- src/sst/elements/ember/test/loadFAM200
- src/sst/elements/ember/test/runFAMloadfile
> add a random get FAM motif

- src/sst/elements/ember/Makefile.am
Correct failing Make Dist from Makefile.am typo
> Makefile.am typo

- src/sst/elements/memHierarchy/cacheArray.h
- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheEventProcessing.cc
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/memoryController.h
Also correct the memory interleave parameters.
> memH: Allow arbitrary interleaving for distributed caches. 

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/ember.cc
- src/sst/elements/ember/emberFamAddrMapper.h
- src/sst/elements/ember/embergen.cc
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/shmem/emberShmemGen.h
- src/sst/elements/ember/shmem/motifs/emberShmemFAM_AtomicInc.h
- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/generateNidListRandom.py
- src/sst/elements/ember/test/loadFileParse.py
- src/sst/elements/firefly/hades.cc
- src/sst/elements/firefly/hadesSHMEM.h
- src/sst/elements/firefly/nicRecvMachine.h
- src/sst/elements/firefly/virtNic.h
- src/sst/elements/hermes/msgapi.h
> FIX SHMEM global network addressing

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/test/generateNidListGroup.py
> add new nid list generator

- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/networkConfig.py
- src/sst/elements/ember/test/paramFiles/8k_dragonflyParams.py
- src/sst/elements/ember/test/paramFiles/8k_fattreeParams.py
- src/sst/elements/ember/test/paramFiles/8k_hyperxParams.py
> support complete topology configuration from param files

- src/sst/elements/firefly/memoryModel/memUnit.h
- src/sst/elements/firefly/memoryModel/simpleMemoryModel.h
> add statistics to MemUnit

- src/sst/elements/ember/test/emberLoad.py
add support to EmberLoad so user can specify custom statistics module
> add statistics module support to emberLoad

- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/loadFileParse.py
- src/sst/elements/ember/test/loadInfo.py
- src/sst/elements/ember/tests/refFiles/test_embernightly.out
Support passing variables to LoadFileParse for the command line
> Enhance load files

- src/sst/elements/ember/emberFamAddrMapper.h
- src/sst/elements/ember/shmem/motifs/emberShmemFAM_AtomicInc.h
- src/sst/elements/firefly/nic.cc
> fix fam atomic inc

- src/sst/elements/ember/Makefile.am
- src/sst/elements/firefly/Makefile.am
Makefile.am adds for Make Dist
> John4 make am

- src/sst/elements/ember/shmem/motifs/emberShmemFAM_AtomicInc.h
- src/sst/elements/firefly/shmem/famAddrMapper.h
> Some FAM improvements

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/ember.cc
- src/sst/elements/ember/emberdetailedcomputeev.h
- src/sst/elements/ember/embergen.cc
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/shmem/motifs/emberShmemAtomicIncV2.h
- src/sst/elements/firefly/nic.cc
- src/sst/elements/thornhill/detailedCompute.h
- src/sst/elements/thornhill/singleThread.cc
- src/sst/elements/thornhill/singleThread.h
> New AtomicInc that uses Detailed Memory Model

- src/sst/elements/simpleElementExample/Makefile.am
- src/sst/elements/simpleElementExample/simpleParamComponent.cc
- src/sst/elements/simpleElementExample/tests/test_simpleParamComponent.py
Add some print outs for simpleParamComponent to check Param handling.
> Additional Print Outs of Params in simpleParamComponent

- CONTRIBUTORS.TXT
- LICENSE
- README.md
- configure.ac
Update main license info to 2019. We can change other files later but this is the main stuff.
> Update main LICENSE files and Information

- src/sst/elements/ember/test/emberLoad.py
- src/sst/elements/ember/test/networkConfig.py
> add JSON topo support

- src/sst/elements/ember/shmem/emberShmemGetEv.h
- src/sst/elements/ember/shmem/emberShmemPutEv.h
- src/sst/elements/firefly/hadesSHMEM.cc
- src/sst/elements/firefly/hadesSHMEM.h
- src/sst/elements/firefly/shmem/alltoall.cc
- src/sst/elements/firefly/shmem/alltoalls.cc
- src/sst/elements/firefly/shmem/broadcast.cc
- src/sst/elements/firefly/shmem/collect.cc
- src/sst/elements/firefly/shmem/fcollect.cc
- src/sst/elements/firefly/shmem/reduction.cc
- src/sst/elements/hermes/shmemapi.h
create a structure for each SHMEM API call and keep the info for duration of call
> reorg hades shmem

- src/sst/elements/shogun/Makefile.am
Add missing enries to Makefile.am
> 4mk file am

- src/sst/elements/ember/Makefile.am
Update Ember Makefile.am so make dist works
(It still has the problem with PIN on sst-test2
> 4 ember md

- src/sst/elements/shogun/tests/refFiles/test_shogun_hierarchy_test.out
> Reference File Update 2

- src/sst/elements/shogun/arb/shogunrrarb.cc
- src/sst/elements/shogun/shogun.cc
- src/sst/elements/shogun/shogun_nic.cc
- src/sst/elements/shogun/shogun_stat_bundle.h
> C int Type Support

- CONTRIBUTING.md
Revise GNU documentation artifacts.
Update GNU artifacts for SST 9.0.0
> Update GNU artifacts

- config/sst_check_cuda.m4
- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/ariel_shmem.h
- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcore.h
- src/sst/elements/ariel/arielcpu.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/arielevent.h
- src/sst/elements/ariel/configure.m4
- src/sst/elements/ariel/frontend/simple/fesimple.cc
Removed Cuda dependency from Ariel and fesimple
> Fix for host_define

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ariel/arielcpu.h
- src/sst/elements/ariel/frontend/simple/fesimple.cc
Removed/moved most of the debug statements from the GPU integration
> Debug Cleaning

- config/sst_check_hybridsim.m4
Fix for https://github.com/sstsimulator/sst-elements/issues/453
> Add DRAMSim and NVDIMMSim deps to HybridSim

- config/sst_check_hybridsim.m4
Fixes an issue with configure failure in Bug #1325.
> Fix HybridSim configuration. Bug #1325

- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/hr_router/xbar_arb_age.h
- src/sst/elements/merlin/hr_router/xbar_arb_lru.h
- src/sst/elements/merlin/hr_router/xbar_arb_lru_infx.h
- src/sst/elements/merlin/hr_router/xbar_arb_rand.h
- src/sst/elements/merlin/hr_router/xbar_arb_rr.h
- src/sst/elements/merlin/portControl.cc
- src/sst/elements/merlin/portControl.h
- src/sst/elements/merlin/router.h
PortControl is not a subcomponent that implements the API
in PortControlBase.  hr_router loads it specifically using
loadAnonymouseSubComponent.  Allowing it to be loaded as a
named subcomponent will come later.
> Made PortControl a SubComponent.

- src/sst/elements/firefly/Makefile.am
> fix make list

- src/sst/elements/ember/test/generateNidListQOS.py
- src/sst/elements/ember/test/loadQOS
- src/sst/elements/ember/test/paramUtils.py
- src/sst/elements/merlin/Makefile.am
- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/interfaces/linkControl.cc
- src/sst/elements/merlin/interfaces/linkControl.h
- src/sst/elements/merlin/interfaces/output_arb_basic.h
- src/sst/elements/merlin/interfaces/output_arb_qos_multi.h
- src/sst/elements/merlin/interfaces/portControl.cc
- src/sst/elements/merlin/interfaces/portControl.h
- src/sst/elements/merlin/pymerlin.py
- src/sst/elements/merlin/router.h
- src/sst/elements/merlin/test/nic.cc
- src/sst/elements/merlin/test/nic.h
- src/sst/elements/merlin/test/pt2pt/pt2pt_test.cc
- src/sst/elements/merlin/test/pt2pt/pt2pt_test.h
Added QoS support to merlin.  Also added files to ember load infrastructure to make enabling QoS for ember runs easier.
> Merlin qos

- config/sst_check_gpgpusim.m4
Replacing the awk script with sed.
> Removing awk from autoconf

- src/sst/elements/miranda/mirandaMemMgr.h
> Miranda: Write SharedRegion in one chunk 

- src/sst/elements/ariel/arielcore.cc
Updating paths and classes for name change.
> Updating For Balar

- src/sst/elements/ember/test/EmberEP.py
- src/sst/elements/firefly/nic.cc
- src/sst/elements/merlin/interfaces/linkControl.cc
- src/sst/elements/merlin/interfaces/reorderLinkControl.cc
- src/sst/elements/zodiac/test/allreduce/allreduce.py
Fixed several bugs in getting ReorderLinkControl working with the new ember changes.
> Ember merlin fix

- src/sst/elements/ember/tests/qos-dragonfly.sh
- src/sst/elements/ember/tests/qos-fattree.sh
- src/sst/elements/ember/tests/qos-hyperx.sh
- src/sst/elements/ember/tests/qos.load
- src/sst/elements/ember/tests/refFiles/test_qos-dragonfly.out
- src/sst/elements/ember/tests/refFiles/test_qos-fattree.out
- src/sst/elements/ember/tests/refFiles/test_qos-hyperx.out
- src/sst/elements/merlin/hr_router/hr_router.cc
Fixed bug in manually setting VNs in hr_router.
Added qos tests to ember.
> Vc init fix

- src/sst/elements/firefly/nicRecvStream.cc
> break recursive cycle

- src/sst/elements/ember/tests/refFiles/test_qos-hyperx.out
Make ref File match on the qos hyperx test
> twk ref file

- src/sst/elements/merlin/merlin.cc
- src/sst/elements/merlin/pymerlin.py
- src/sst/elements/merlin/topology/hyperx.cc
Fixes to support use of user loaded topology objects.  Also first cut at Python 3 support.
> Merlin python update

- src/sst/elements/prospero/Makefile.am
- src/sst/elements/prospero/proscpu.h
- src/sst/elements/prospero/tracetool/sstmemtrace.cc
Disabling compile with zlib if building using PIN3
> Changes to prospero to support PIN3

- src/sst/elements/ariel/arielcore.cc
- src/sst/elements/ember/mpi/motifs/emberdetailedstream.cc
- src/sst/elements/memHierarchy/networkMemInspector.cc
- src/sst/elements/memHierarchy/networkMemInspector.h
- src/sst/elements/merlin/inspectors/circuitCounter.cc
- src/sst/elements/merlin/inspectors/circuitCounter.h
- src/sst/elements/merlin/inspectors/testInspector.cc
- src/sst/elements/merlin/inspectors/testInspector.h
- src/sst/elements/merlin/interfaces/linkControl.h
- src/sst/elements/merlin/interfaces/reorderLinkControl.cc
- src/sst/elements/merlin/interfaces/reorderLinkControl.h
- src/sst/elements/shogun/shogun_nic.cc
- src/sst/elements/shogun/shogun_nic.h
- src/sst/elements/simpleElementExample/simpleClockerComponent.cc
- src/sst/elements/simpleElementExample/simpleClockerComponent.h
Removed last references to PREVIEW_BUILD.
Removed use of newly deprecated functions in simulation.
Removed use of OneShot from simpleClockerComponent in simpleElementExample.
> Some general cleanup on elements.

- src/sst/elements/ember/test/cramsimDetailedModelParams.py
- src/sst/elements/ember/test/detailedShmemModel.py
- src/sst/elements/ember/test/runFAMloadfileDetailed
- src/sst/elements/ember/test/timingDetailedModelParams.py
Added configuration files that the detailed SHMEM model can use for timingDRAM and Cramsim.
> Added timingDRAM and Cramsim models to the detail SHMEM runner

- src/sst/elements/ember/pyember.py
- src/sst/elements/firefly/virtNic.h
- src/sst/elements/merlin/pymerlin-base.py
- src/sst/elements/merlin/pymerlin-endpoint.py
- src/sst/elements/merlin/topology/pymerlin-topo-dragonfly.py
- src/sst/elements/merlin/topology/pymerlin-topo-fattree.py
- src/sst/elements/merlin/topology/pymerlin-topo-hyperx.py
- src/sst/elements/merlin/topology/pymerlin-topo-mesh.py
Updates to beta version of new ember and merlin python modules.
> Ember merlin python

- src/sst/elements/firefly/funcSM/scatterv.cc
- src/sst/elements/firefly/funcSM/scatterv.h
> add support for root != 0 to firefly scatter

- src/sst/elements/memHierarchy/memHierarchyInterface.cc
1. Inv messages to core from L1 (if enabled)
2. Extra sanity checks when debug enabled
> memH: Update interface

- src/sst/elements/memHierarchy/tests/refFiles/test_memHA_BackendHBMDramsim_MC.out
- src/sst/elements/memHierarchy/tests/refFiles/test_memHA_HashXor_MC.out
> memH: Fix ref files

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/mpi/motifs/emberNtoM.cc
- src/sst/elements/ember/mpi/motifs/emberNtoM.h
> Ember N to M

- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/memHierarchy/tests/testNoninclusive-1.py
- src/sst/elements/memHierarchy/tests/testNoninclusive-2.py
> memH: Adjust memory controller's region to min of region and mem_size

- src/sst/elements/vanadis/inst/vinst.h
- src/sst/elements/vanadis/os/node/vnodeoswritevh.h
- src/sst/elements/vanadis/tests/basic_vanadis.py
- src/sst/elements/vanadis/vanadis.cc
Improves performance for instruction issue pipeline stage.
> Performance Improvement to Vanadis Core

- src/sst/elements/vanadis/decoder/vdecoder.h
- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/vanadis.h
- General code tidy up for unused functions
- Provide performance improvements for tracking register demands in pending instructions (queued for issue)
- Guard some print outs to improve performance
> Performance Improvement for Register Renaming Stage of Vanadis Core

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/memHierarchy/tests/testsuite_default_memHierarchy_memHSieve.py
- src/sst/elements/simpleElementExample/Makefile.am
- src/sst/elements/simpleSimulation/Makefile.am
- src/sst/elements/zodiac/Makefile.am
- src/sst/elements/zodiac/test/testsuite_default_SiriusZodiacTrace.py
Fixed missing distribution files and a new frameworks test issue on memHSieve.
> Fixing distribution errors and minor memHSieve test issue.

- src/sst/elements/vanadis/Makefile.am
Fixes an issue with `make dist` builds for Vanadis.
> Fix make dist header files for Vanadis

- src/sst/elements/merlin/Makefile.am
- src/sst/elements/merlin/hr_router/hr_router.cc
- src/sst/elements/merlin/hr_router/hr_router.h
- src/sst/elements/merlin/interfaces/linkControl.cc
- src/sst/elements/merlin/interfaces/linkControl.h
- src/sst/elements/merlin/interfaces/portControl.cc
- src/sst/elements/merlin/interfaces/portControl.h
- src/sst/elements/merlin/pymerlin-base.py
- src/sst/elements/merlin/pymerlin-endpoint.py
- src/sst/elements/merlin/router.h
- src/sst/elements/merlin/test/simple_patterns/incast.cc
- src/sst/elements/merlin/test/simple_patterns/incast.h
- src/sst/elements/merlin/tests/dragon_128_platform_test_cm.py
- src/sst/elements/merlin/tests/dragon_128_test.py
- src/sst/elements/merlin/tests/platform_file_dragon_128.py
- src/sst/elements/merlin/tests/refFiles/test_merlin_dragon_128_platform_test.out
- src/sst/elements/merlin/tests/refFiles/test_merlin_dragon_128_platform_test_cm.out
- src/sst/elements/merlin/tests/testsuite_default_merlin.py
- src/sst/elements/merlin/topology/dragonfly.cc
- src/sst/elements/merlin/topology/dragonfly.h
- src/sst/elements/merlin/topology/pymerlin-topo-dragonfly.py
First cut at congestion management.  Only supports dragonfly for now.
> Merlin cong mgmt

- src/sst/elements/merlin/tests/dragon_128_platform_test_cm.py
- src/sst/elements/merlin/tests/refFiles/test_merlin_dragon_128_platform_test_cm.out
Updated test to not use random allocation because it causes differences between py2 and py3.
> Merlin test update

- src/sst/elements/merlin/pymerlin-base.py
adding _allocate_system to pymerlin-base.py
> adding allocate system

- src/sst/elements/CramSim/c_Controller.cpp
- src/sst/elements/CramSim/c_Dimm.cpp
- src/sst/elements/CramSim/c_TxnGen.cpp
- src/sst/elements/Samba/PageTableWalker.h
Clean up some build warnings found on OSX.
> Cleanup build warnings

- src/sst/elements/memHierarchy/Sieve/sieveController.cc
- src/sst/elements/memHierarchy/Sieve/sieveController.h
- src/sst/elements/memHierarchy/Sieve/sieveFactory.cc
- src/sst/elements/memHierarchy/bus.cc
- src/sst/elements/memHierarchy/memNICFour.cc
- src/sst/elements/miranda/tests/copybench.py
- src/sst/elements/miranda/tests/gupsgen.py
- src/sst/elements/miranda/tests/inorderstream.py
- src/sst/elements/miranda/tests/randomgen.py
- src/sst/elements/miranda/tests/revsinglestream.py
- src/sst/elements/miranda/tests/singlestream.py
- src/sst/elements/miranda/tests/spmvgen.py
- src/sst/elements/miranda/tests/stencil3dbench.py
- src/sst/elements/miranda/tests/streambench.py
- src/sst/elements/miranda/tests/test_subcomp.py
Remove uses of internal core functions in memH
Update Miranda tests so they pass in debug mode too
> MemH fixes, Miranda test updates

- src/sst/elements/firefly/merlinEvent.h
- src/sst/elements/firefly/nicRecvMachine.h
handle control pack in special case
> Fix firefly

- src/sst/elements/ember/pyember.py
> Fixed a typo in string in ember for global param set.

- src/sst/elements/thornhill/Makefile.am
> hermes needs these headers to be installed

- configure.ac
Removes warnings with autoconf 2.71
> Fix warnings with Autoconf 2.71

- src/sst/elements/memHierarchy/Makefile.am
- src/sst/elements/prospero/Makefile.am
- src/sst/elements/zodiac/Makefile.am
PR to address missing test reference files (from distribution) indicated in Issue #1688
> Changes to fix missing distribution files needed for testing

- src/sst/elements/vanadis/datastruct/vcache.h
Add const qualifiers to functions in Vanadis LRU cache.
> Add const qualifiers to functions in Vanadis LRU cache

- src/sst/elements/vanadis/inst/regfile.h
Optimized register file access code (shorten sequence).
> Vanadis Rework for Code for Register File Access

- config/sst_check_llvm_config.m4
Previous test would sometimes return a false positive
> Fixes for --with-llvm test

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vbcmp.h
- src/sst/elements/vanadis/inst/vbcmpi.h
- src/sst/elements/vanadis/inst/vbcmpil.h
- src/sst/elements/vanadis/inst/vbfp.h
- src/sst/elements/vanadis/inst/vjl.h
- src/sst/elements/vanadis/inst/vjlr.h
- src/sst/elements/vanadis/inst/vjr.h
- src/sst/elements/vanadis/inst/vjump.h
- src/sst/elements/vanadis/inst/vspeculate.h
Overhaul how instructions are passed to pipeline for speculative instructions for Vanadis.
> Vanadis - overhaul how instructions are passed to pipeline for speculative instructions 

- src/sst/elements/memHierarchy/bus.cc
- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_Shared_Noninclusive.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.cc
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.h
- src/sst/elements/memHierarchy/memoryCacheController.cc
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/memHierarchy/scratchpad.cc
- src/sst/elements/memHierarchy/standardInterface.cc
- src/sst/elements/memHierarchy/tests/testsuite_default_memHierarchy_sdl.py
- src/sst/elements/memHierarchy/util.h
fix bug in MMIO addressing, debug output updates, fix error in test suite
> memH: various updates

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- Adds support for `RVC.FLD` instructions (first loads to floating point)
- Additional 32b shift instructions
- Fixes bug in `MULW`
> Additional RISCV Instruction Support

- README.md
Update copyright to 2022 for `README`
> Test PR Engine - Update README Copyright to 2022

- src/sst/elements/vanadis/datastruct/cqueue.h
- src/sst/elements/vanadis/decoder/vdecoder.h
- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/regfile.h
- src/sst/elements/vanadis/inst/vfp2gpr.h
- src/sst/elements/vanadis/inst/vfpadd.h
- src/sst/elements/vanadis/inst/vfpconv.h
- src/sst/elements/vanadis/inst/vfpinst.h
- src/sst/elements/vanadis/inst/vfpmul.h
- src/sst/elements/vanadis/inst/vfpscmp.h
- src/sst/elements/vanadis/inst/vfpsub.h
- src/sst/elements/vanadis/inst/vgpr2fp.h
- src/sst/elements/vanadis/inst/vmipsfpscmp.h
- src/sst/elements/vanadis/lsq/vlsq.h
- src/sst/elements/vanadis/lsq/vlsqseq.h
- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/vanadis.h
Run `clang-format` over lots of Vanadis files.
> Formatting Update for Vanadis

- src/sst/elements/vanadis/decoder/vmipsdecoder.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/inst/vdivmod.h
- src/sst/elements/vanadis/inst/vmod.h
- Generates more efficient code for `DIVMOD` and `MOD` micro-ops
> Vanadis Update to Migrate DIVMOD and MOD Micro-Ops to More Efficient Code Generation

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- Add support for fence instructions
> Add Support for Fence Instructions in Vanadis

- src/sst/elements/rdmaNic/rdmaNic.cc
- src/sst/elements/rdmaNic/rdmaNic.h
- src/sst/elements/rdmaNic/rdmaNicCmds.h
- src/sst/elements/rdmaNic/rdmaNicHostInterface.h
- src/sst/elements/rdmaNic/rdmaNicRecvEngine.h
- src/sst/elements/rdmaNic/tests/app/rdma/include/rdma.h
- src/sst/elements/rdmaNic/tests/app/rdma/msg.c
- src/sst/elements/rdmaNic/tests/app/rdma/msg.out.gold
- src/sst/elements/rdmaNic/tests/app/rdma/msg.stdout-node0.cpu0.os.gold
- src/sst/elements/rdmaNic/tests/app/rdma/msg.stdout-node1.cpu0.os.gold
- src/sst/elements/rdmaNic/tests/app/rdma/src/rdma.c
add rdma_destroy_cq and rdma_destroy_rq
> Add RDMA queue destroy support

- src/sst/elements/simpleElementExample/tests/basicStatistics0.py
- src/sst/elements/simpleElementExample/tests/basicStatistics1.py
> simpleElemExample: Fix typos in tests

- src/sst/elements/llyr/llyr.cc
- src/sst/elements/llyr/llyrTypes.h
- src/sst/elements/llyr/mappers/llyrMapper.h
- src/sst/elements/llyr/mappers/pyMapper.h
- src/sst/elements/llyr/mappers/simpleMapper.h
- src/sst/elements/llyr/parser/parser.cc
- src/sst/elements/llyr/pes/intPE.h
- src/sst/elements/llyr/pes/loadPE.h
- src/sst/elements/llyr/pes/storePE.h
Added streaming loads and stores to PE list
> Support for streaming memory operations via new PEs

- src/sst/elements/llyr/parser/parser.cc
Switch mapper input to dot format
> Switch to dot format

- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.cc
Added missing parentheses in `MESI_L1.cc`
> memH: Bug fix in MESI_L1

- src/sst/elements/cassini/cacheLineTrack.cc
- src/sst/elements/cassini/cacheLineTrack.h
Should fix issue #1909 but lacking enough details to verify/test. (But improvement in code quality regardless.)
> Remove usage of "uint" from cassini. Addresses issue #1909

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/mpi/motifs/emberBFS.cc
- src/sst/elements/ember/mpi/motifs/emberBFS.h
- src/sst/elements/ember/test/defaultSim.py
> new-bfs-models-2

- src/sst/elements/vanadis/os/node/vnodemmaph.h
- src/sst/elements/vanadis/os/node/vnodeosstattype.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vnodeos.h
- src/sst/elements/vanadis/os/vnodeoshandler.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- fix some valgrind errors for uninitialized variables
- support fstat in RISCV
- add madvise, ( it does nothing and return 0, same as MIPS)
- change some debug levels in the OS
- fix bug in mmap where FD is not -1
> Vanadis fixes 

- src/sst/elements/vanadis/inst/vpartialstore.h
- src/sst/elements/vanadis/lsq/vbasiclsq.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- src/sst/elements/vanadis/tests/small/basic-io/hello-world-cpp/mipsel/sst.stdout.gold
Fix MIPS SWR and SWL in PartialStore.
Drop LARGEFILE flag when running OSX
> Vanadis fixes

- src/sst/elements/vanadis/lsq/vbasiclsqentry.h
Change the load/store conflict detection in Vanadis.
> Change overlap detection in load/store for Basic LSQ in Vanadis

- src/sst/elements/ember/mpi/motifs/emberBFS.cc
- src/sst/elements/ember/mpi/motifs/emberBFS.h
This PR updates the Ember BFS motifs to use 2D models.
> 2D BFS Models

- src/sst/elements/vanadis/datastruct/vcache.h
- src/sst/elements/vanadis/vinsloader.h
Fix up delete within the cache data structure for Vanadis
> Fix up delete within the cache data structure for Vanadis

- src/sst/elements/osseous/Makefile.am
- src/sst/elements/osseous/README.md
- src/sst/elements/osseous/rtl_header.h
- src/sst/elements/osseous/rtlcomponent.cc
- src/sst/elements/osseous/tests/Makefile
- src/sst/elements/osseous/tests/runstream.py
- src/sst/elements/osseous/tests/testbench.c
> Modified Osseous for vecshift example and added missing files

- src/sst/elements/Messier/tests/testsuite_default_Messier.py
- src/sst/elements/memHierarchy/memEvent.h
Also increase messier test timeout
> memH: Fix bug in LLSC 

- src/sst/elements/ember/emberengine.cc
Put nullptr check before use of ptr
> fix nullptr check in ember, addresses issue #2007

- src/sst/elements/mercury/tests/build.sh
Use sst-config to gather correct directories, flags, etc.
---
* If testing passes, the source branch will be …
> update mercury build.sh

- src/sst/elements/vanadis/lsq/vbasiclsq.h
The LSQ was not incrementing the iterator in some cases.
> Vanadis LSQ bug fix

- src/sst/elements/vanadis/vanadis.cc
Fix bug where an SST event was being freed twice.
> Vanadis bug fix

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/embergen.h
- src/sst/elements/ember/libs/emberMpiLib.h
- src/sst/elements/ember/mpi/embermpigen.h
- src/sst/elements/ember/mpi/motifs/README-tricount.txt
- src/sst/elements/ember/mpi/motifs/embertricount.cc
- src/sst/elements/ember/mpi/motifs/embertricount.h
- src/sst/elements/ember/mpi/motifs/embertricount_setup.cc
- src/sst/elements/ember/test/tricount.py
- src/sst/elements/firefly/funcSM/collectiveOps.h
- src/sst/elements/firefly/info.h
- src/sst/elements/hermes/msgapi.h
Add initial version of tricount ember motif. Includes minor changes/improvements to hermes/firefly, most importantly adding more data types.
> add tricount motif

- src/sst/elements/ember/Makefile.am
- src/sst/elements/ember/mpi/motifs/embertricount.cc
- src/sst/elements/ember/mpi/motifs/embertricount.h
- src/sst/elements/ember/test/tricount.py
- src/sst/elements/ember/tools/embertricount/embertricount_setup.cc
tricount data requests based on edge rank instead of vertex, added setup build and many bug fixes
> Tricount improvements and bug fixes (data requests based on edges)

- src/sst/elements/ember/mpi/motifs/README-tricount.txt
Update README for tricount motif
> Update tricount readme

- src/sst/elements/ember/mpi/motifs/emberBFS.cc
- src/sst/elements/ember/mpi/motifs/emberBFS.h
This commit updates emberBFS to add support for a few new types of models: exponential, constant, bilinear, and trace-based models.
Model files are available in the a-sst repository. 
This PR is associated with https://github.com/sstsimulator/a-sst/pull/2
> Add support for exponential and trace models to emberBFS

- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/coherencemgr/Incoherent_L1.cc
- src/sst/elements/memHierarchy/coherencemgr/Incoherent_L1.h
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.h
- src/sst/elements/memHierarchy/lineTypes.h
Add ability to guarantee LLSC forward progress for RISC-V architectures
> Memh: LL/SC forward progress fix

- src/sst/elements/vanadis/os/vcpuos.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
create a template for the OS handler class where we can specify the integer size and base registers offsets
> Vanadis: Template the OS Handler

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/lsq/vbasiclsq.h
- src/sst/elements/vanadis/os/include/process.h
- src/sst/elements/vanadis/os/syscall/fstatat.h
- src/sst/elements/vanadis/os/syscall/getaffinity.h
- src/sst/elements/vanadis/os/syscall/kill.h
- src/sst/elements/vanadis/os/syscall/mmap.h
- src/sst/elements/vanadis/os/syscall/prlimit.h
- src/sst/elements/vanadis/os/syscall/read.h
- src/sst/elements/vanadis/os/syscall/readlinkat.h
- src/sst/elements/vanadis/os/syscall/syscall.cc
- src/sst/elements/vanadis/os/vcpuos2.h
- src/sst/elements/vanadis/os/vmipscpuos.h
- src/sst/elements/vanadis/os/vnodeos.cc
- src/sst/elements/vanadis/os/vriscvcpuos.h
- src/sst/elements/vanadis/vanadis.cc
> Vanadis: fix compiler warnings

- src/sst/elements/mmu/simpleMMU.cc
- src/sst/elements/mmu/simpleMMU.h
- src/sst/elements/mmu/simpleTLB.cc
- src/sst/elements/mmu/simpleTLB.h
> MMU: fix compiler warnings

- src/sst/elements/vanadis/lsq/vbasiclsq.h
- src/sst/elements/vanadis/os/syscall/syscall.h
- LSQ was not setting HW thread
- syscall memory write was signaling completion before resp, this doesn't work for Store Conditional
> Vanadis: bug fixes

- README.md
- src/sst/elements/README.md
> Link to documentation website

- src/sst/elements/rdmaNic/rdmaNic.cc
- src/sst/elements/rdmaNic/rdmaNic.h
- src/sst/elements/rdmaNic/rdmaNicHostInterface.h
- src/sst/elements/rdmaNic/tests/app/rdma/include/base.h
- src/sst/elements/rdmaNic/tests/app/rdma/msg.out.gold
- src/sst/elements/rdmaNic/tests/app/rdma/src/base.c
- src/sst/elements/rdmaNic/tests/app/rdma/src/rdma.c
The interface between the Host and NIC was not well organized in the NIC. Cleanup the data structures.
> RDMA NIC: cleanup 

- src/sst/elements/vanadis/inst/vjlr.h
- src/sst/elements/vanadis/vanadis.cc
- src/sst/elements/vanadis/vanadisDbgFlags.h
- Fix a bug with instruct jlr where it wasn't adding the imm.
- add node id to debug printout
- create a debug flag for Retire
> Vanadis: fix bug with JLR

- src/sst/elements/vanadis/tests/boom_vanadis-kingsley.py
New vanadis example using kingsley instead of merlin
> vanadis model using kingsley

- src/sst/elements/ember/mpi/motifs/embertricount.cc
- src/sst/elements/ember/mpi/motifs/embertricount.h
Properly handle isend requests in EmberTriCountGenerator.
Addresses issue #2155
> Properly handle isend requests in EmberTriCountGenerator.

- src/sst/elements/ember/mpi/motifs/embertricount.cc
- src/sst/elements/ember/mpi/motifs/embertricount.h
fix null request bug and add constant degree option in tricount
> ember: fix null request bug and add constant degree option in tricount

- src/sst/elements/ember/mpi/motifs/emberotf2.cc
- src/sst/elements/ember/mpi/motifs/emberotf2.h
This pull request fixes #2124 related to the compilation issue. 
Tests for set-elements are not built with --with-otf or --with-otf2 so will pass.
> Fixed issue with OTF2 Motif not building due to Ember changes.

- src/sst/elements/rdmaNic/rdmaNic.cc
- src/sst/elements/rdmaNic/rdmaNicCmds.h
- src/sst/elements/rdmaNic/rdmaNicRecvEngine.cc
- src/sst/elements/rdmaNic/rdmaNicRecvEngine.h
Fixed warnings in element rdmaNic and mmu.
> fix warnings

- src/sst/elements/ember/mpi/motifs/emberTrafficGen.cc
- src/sst/elements/ember/mpi/motifs/emberTrafficGen.h
- src/sst/elements/ember/test/trafficgen.py
- src/sst/elements/firefly/ctrlMsgProcessQueuesState.cc
Added random traffic pattern with hotspots feature to trafficgen ember motif.
> Ember: extended available patterns in trafficgen motif

- src/sst/elements/memHierarchy/cacheController.cc
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_L1.h
- src/sst/elements/memHierarchy/coherencemgr/coherenceController.h
- src/sst/elements/memHierarchy/lineTypes.h
- src/sst/elements/memHierarchy/memEvent.h
- src/sst/elements/memHierarchy/memEventBase.h
> memH: Fix LL/SC bug that allowed livelock

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/os/callev/voscallfutex.h
- src/sst/elements/vanadis/os/include/fdTable.h
- src/sst/elements/vanadis/os/include/virtMemMap.h
- src/sst/elements/vanadis/os/syscall/clone.cc
- src/sst/elements/vanadis/os/syscall/clone.h
- src/sst/elements/vanadis/os/syscall/exit.cc
- src/sst/elements/vanadis/os/syscall/fork.cc
- src/sst/elements/vanadis/os/syscall/futex.cc
- src/sst/elements/vanadis/os/syscall/futex.h
- src/sst/elements/vanadis/os/syscall/mmap.h
- src/sst/elements/vanadis/os/syscall/syscall.h
- src/sst/elements/vanadis/os/vphysmemmanager.h
- src/sst/elements/vanadis/os/vriscvcpuos.h
- src/sst/elements/vanadis/tests/basic_vanadis.py
The changes add changes to fork/clone/exit/futex so they support glibc
> Vanadis changes to support glibc 

- src/sst/elements/ember/mpi/motifs/embertricount.cc
fix corner case for taskStarts indexing
> tricount: fix taskStarts indexing

- src/sst/elements/vanadis/Makefile.am
- src/sst/elements/vanadis/tests/riscv-tests/README
- src/sst/elements/vanadis/tests/riscv-tests/patch.txt
- src/sst/elements/vanadis/tests/riscv-tests/run-riscv-tests
- src/sst/elements/vanadis/tests/riscv-tests/run-riscv-tests.out
Add instructions and supporting files to build and run the RISCV test suite
> add RISCV suite

- src/sst/elements/vanadis/decoder/vriscv64decoder.h
> decode rdcycle

- config/sst_core_check_install.m4
- configure.ac
- src/sst/elements/simpleElementExample/Makefile.am
- src/sst/elements/simpleElementExample/basicSimLifeCycle.h
- src/sst/elements/simpleElementExample/sst-snippets.json
Added support for source code snippetting:
1) Configure detects presence of sst-snippets.py script in core install
2) Added new recursive target "snippets"
3) simpleElementExample has example make targets and snippet config file
> Added support for source code snippetting.

- src/sst/elements/vanadis/os/syscall/futex.cc
- src/sst/elements/vanadis/os/syscall/futex.h
Update futex wake to wake all waiters instead of just one. Issue #2319.
> Update futex wake to wake multiple waiters.

- src/sst/elements/mask-mpi/tests/testsuite_default_mask_mpi.py
- src/sst/elements/mercury/tests/testsuite_default_hg.py
- src/sst/elements/merlin/pymerlin-base.py
Remove calls to sst-config (get info from test framework)
Fix string issue in merlin
> minor fixes to merlin,mercury,mask-mpi

- src/sst/elements/ember/run/configurations/3LevelModel.py
- src/sst/elements/ember/run/configurations/3LevelModelParams.py
- src/sst/elements/ember/run/configurations/basicDetailedModel.py
- src/sst/elements/ember/run/configurations/basicDetailedModelParams.py
- src/sst/elements/ember/run/configurations/defaultSim.py
- src/sst/elements/ember/run/configurations/detailedSim.py
- src/sst/elements/ember/run/configurations/detailedStreamSim.py
- src/sst/elements/ember/run/configurations/sandyBridgeModel.py
- src/sst/elements/ember/run/configurations/sandyBridgeModelParams.py
- src/sst/elements/ember/run/configurations/sandySim.py
- src/sst/elements/memHierarchy/membackend/backing.h
- src/sst/elements/mmu/simpleMMU.cc
- src/sst/elements/mmu/simpleMMU.h
- src/sst/elements/vanadis/decoder/vriscv64decoder.h
- src/sst/elements/vanadis/os/include/fdTable.h
- src/sst/elements/vanadis/os/include/process.h
- src/sst/elements/vanadis/os/syscall/clone.cc
- src/sst/elements/vanadis/os/syscall/exit.cc
- src/sst/elements/vanadis/os/vnodeos.cc
- src/sst/elements/vanadis/os/vphysmemmanager.h
- src/sst/elements/vanadis/vanadis.cc
Compile warnings
Some missing copyright date updates
> Fix compile warnings

- src/sst/elements/vanadis/tests/basic_vanadis.py
- src/sst/elements/vanadis/tests/boom_vanadis-kingsley.py
Update and fix the kingsley script
Clean the default script
> Fixes for Vanadis Config Scripts

- src/sst/elements/memHierarchy/bus.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_Inclusive.cc
- src/sst/elements/memHierarchy/coherencemgr/MESI_Shared_Noninclusive.cc
- src/sst/elements/memHierarchy/memNICBase.h
- src/sst/elements/memHierarchy/memNICFour.cc
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/mshr.cc
Also improve debug output format
> Fix coherence protocol bug in noninclusive shared cache

- src/sst/elements/iris/sumi/sim_transport.cc
- src/sst/elements/mask-mpi/mpi_api.cc
- src/sst/elements/mask-mpi/tests/platform_file_mask_mpi_test.py
- src/sst/elements/mask-mpi/tests/refFiles/test_allgather.out
- src/sst/elements/mask-mpi/tests/refFiles/test_alltoall.out
- src/sst/elements/mask-mpi/tests/refFiles/test_halo3d26.out
- src/sst/elements/mask-mpi/tests/refFiles/test_reduce.out
- src/sst/elements/mask-mpi/tests/refFiles/test_sendrecv.out
- src/sst/elements/mercury/components/nic.cc
- src/sst/elements/mercury/libraries/compute/instruction_processor.cc
- src/sst/elements/mercury/libraries/compute/memory_model.cc
- src/sst/elements/mercury/pymercury.py
> Mercury: parameter clean-up

- src/sst/elements/ariel/Makefile.am
- src/sst/elements/llyr/Makefile.am
- Fix a bug in llyr build
- Move common flags in ariel build (make it easier to start testing with clang)
- Remove CUDA build items in ariel make
> Cleanup the build a tiny bit

- src/sst/elements/iris/sumi/collective_actor.cc
- src/sst/elements/iris/sumi/communicator.cc
- src/sst/elements/iris/sumi/sim_transport.cc
- src/sst/elements/iris/sumi/transport.h
- src/sst/elements/mask-mpi/mpi_api.cc
- src/sst/elements/mask-mpi/mpi_api.h
- src/sst/elements/mask-mpi/mpi_api_comm.cc
- src/sst/elements/mask-mpi/mpi_comm/mpi_comm_factory.cc
- src/sst/elements/mask-mpi/mpi_comm/mpi_comm_factory.h
- src/sst/elements/mercury/components/nic.cc
- src/sst/elements/mercury/components/node.cc
- src/sst/elements/mercury/components/node_CL.cc
- src/sst/elements/mercury/components/node_base.cc
- src/sst/elements/mercury/components/node_base.h
- src/sst/elements/mercury/components/operating_system.cc
- src/sst/elements/mercury/components/operating_system.h
- src/sst/elements/mercury/components/operating_system_base.h
- src/sst/elements/mercury/libraries/compute/compute_scheduler.cc
- src/sst/elements/mercury/libraries/compute/compute_scheduler.h
- src/sst/elements/mercury/operating_system/launch/app_launcher.cc
- src/sst/elements/mercury/operating_system/launch/app_launcher.h
- src/sst/elements/mercury/operating_system/process/app.cc
- src/sst/elements/mercury/operating_system/process/app.h
- src/sst/elements/mercury/pymercury.py
Mercury: support for multiple tasks per node
> Mercury: support for multiple tasks per node

- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/api/Makefile.am
- src/sst/elements/ariel/configure.m4
- src/sst/elements/ariel/frontend/simple/examples/stream/Makefile
- src/sst/elements/ariel/mpi/Makefile.am
- src/sst/elements/ariel/tests/testsuite_default_Ariel.py
- src/sst/elements/ariel/tests/testsuite_mpi_Ariel.py
- src/sst/elements/ariel/tests/testsuite_testio_Ariel.py
- src/sst/elements/memHierarchy/Makefile.am
Fix for https://github.com/sstsimulator/sst-elements/issues/2491
> Fix for api and mpi file deletion when building in-source

- src/sst/elements/memHierarchy/cacheController.h
- src/sst/elements/memHierarchy/cacheFactory.cc
- src/sst/elements/memHierarchy/membackend/backing.h
- src/sst/elements/memHierarchy/membackend/memBackend.h
- src/sst/elements/memHierarchy/membackend/simpleMemBackend.cc
- src/sst/elements/memHierarchy/membackend/simpleMemBackend.h
- src/sst/elements/memHierarchy/memoryController.cc
- src/sst/elements/memHierarchy/memoryController.h
- src/sst/elements/memHierarchy/standardInterface.cc
- src/sst/elements/memHierarchy/standardInterface.h
- src/sst/elements/memHierarchy/testcpu/standardCPU.cc
- src/sst/elements/memHierarchy/testcpu/standardCPU.h
- src/sst/elements/memHierarchy/tests/testMemh_minimal.py
> Add basic serialization to memh

- config/sst_check_pintool.m4
- src/sst/elements/ariel/Makefile.am
- src/sst/elements/ariel/frontend/pin3/fesimple.cc
- src/sst/elements/ariel/frontend/simple/fesimple.cc
- src/sst/elements/prospero/Makefile.am
- src/sst/elements/prospero/tracetool/sstmemtrace.cc
Closes https://github.com/sstsimulator/sst-elements/issues/2507
> Allow compiling using Clang on Linux with Intel Pin

- src/sst/elements/mercury/operating_system/process/app.cc
- src/sst/elements/mercury/tests/ostest.cc
- src/sst/elements/mercury/tests/ostest.py
- src/sst/elements/mercury/tests/refFiles/ostest.out
Also add some sample usage to the ostest.py example.
> mercury: add support for app arguments

- src/sst/elements/merlin/topology/dragonfly.cc
> Fixes init evs propagation in dragonfly topo 
